### ISSUE TITLE
JS: false positive: `yield import blah`

### ISSUE THREAD

**Issue by Trott** [Semmle/ql#1105]
Following up on https://discuss.lgtm.com/t/false-positive-yield-import-results-in-syntax-error/1883/2 which frustratingly I am unable to post to. (I opened the issue, got a reply with a question, posted my reply to the question, but got told by the interface that my reply would not appear until it was approved by an owner or moderator or staff member or whatever, and then got another reply prodding me to please answer the question I already answered but which apparently will sit in a moderator queue for who-knows-how-long. And now the interface doesn't even offer the **option** of replying. Fortunately, the last reply included a link to this repo so here we are...)

My original report:

> lgtm flags yield import blah as a Syntax Error https://lgtm.com/rules/1800086/ 2. Perhaps lgtm is using acorn-dynamic-imports prior to 2.0.2?

lgtm staff reply:

> could you provide a link to the project in question please?

My reply which never got posted:

> https://lgtm.com/projects/g/ilios/frontend/snapshot/dist-1507417986286-1552400119401/files/app/components/programyear-objective-list.js?sort=name&dir=ASC&mode=heatmap#xa9a0de30b91adc3e:1

Thanks!

**Comment by samlanning** [comment]
@Trott thanks for posting further information and opening an issue here.

Not sure what's happening w.r.t. you being unable to reply (discourse (the software that powers the forum) does some weird stuff when people include links to things etc...) but i'll look into it!

**Comment by xiemaisi** [comment]
Thanks again for reporting this problem. A fix has been merged and should be deployed as part of the next LGTM.com upgrade within the next two weeks or so.

**Comment by xiemaisi** [comment]
The fix has been deployed.
