### ISSUE TITLE
C++/Qt false positive: qRegisterMetatype is not a noop

### ISSUE THREAD

**Issue by tcanabrava** [Semmle/ql#1154]
The tool complains that qRegisterMetatype is a noop, it's not.

https://lgtm.com/projects/g/KDE/okular/snapshot/9755abc39706567915f1d1b757b70e2a0f8e3f3a/files/autotests/parttest.cpp?sort=name&dir=ASC&mode=heatmap#x9525a92bb944ee97:1

**Comment by rdmarsh2** [comment]
I agreed with you at first and went digging to find what we did wrong, but I wound up convincing myself that the result is correct. [`qRegisterMetatype<T>`](https://github.com/qt/qtbase/blob/4daf5204babc62a7ae58b6de5c09c527f81ea27c/src/corelib/kernel/qmetatype.h#L1801) calls `qMetaTypeId<T>()`, which calls `QMetaTypeId2<T>::qt_metatype_id()`. That would normally call `QMetaTypeId<T>::qt_metatype_id()`, but there's a specialization of `QMetaTypeId2` for `QUrl` declared via [`QT_FOR_EACH_STATIC_TYPE(Q_DECLARE_BUILTIN_METATYPE)`](https://github.com/qt/qtbase/blob/4daf5204babc62a7ae58b6de5c09c527f81ea27c/src/corelib/kernel/qmetatype.h#L2276). [`Q_DECLARE_BUILTIN_METATYPE`](https://github.com/qt/qtbase/blob/4daf5204babc62a7ae58b6de5c09c527f81ea27c/src/corelib/kernel/qmetatype.h#L1958) declares a `qt_metatype_id()` with no side effects. As a result, the call to `qRegisterMetatype<QUrl>()` has no side effects.

**Comment by tcanabrava** [comment]
Learning a thing everyday. :)
Thanks for the proactiveness.
