### ISSUE TITLE
JavaScript/TypeScript: false positive Semicolon Insertion in template string

### ISSUE THREAD

**Issue by ajafff** [Semmle/ql#125]
Copied over from https://github.com/lgtmhq/lgtm-queries/issues/50

I don't see where a semicolon would be missing.

```js
if (arg.startsWith('-'))
    throw new ConfigurationError(`Unknown option '${arg}'.`);
```

![image](https://user-images.githubusercontent.com/11968040/44917056-9f2af800-ad37-11e8-84ec-549a326cebe6.png)

**Comment by xiemaisi** [comment]
@asger-semmle, could you take a look at this?

**Comment by xiemaisi** [comment]
Thanks again for your report. We are working on a fix, but in the meantime we have disabled the semicolon insertion rule for TypeScript, so you should not be seeing this alert any more.

**Comment by xiemaisi** [comment]
This has now been fixed and the rule has been re-enabled.
