### ISSUE TITLE
TypeScript: false positive Unused import

### ISSUE THREAD

**Issue by ajafff** [Semmle/ql#126]
In TypeScript it's valid to export an "ImportEqualsDeclaration".

```ts
export import stringify = require('./stringify');

// equivalent to
import stringify = require('./stringify');
export {stringify};
```

Currently this is reported as unused:
https://lgtm.com/projects/g/DefinitelyTyped/DefinitelyTyped/snapshot/d798d9208fc79327a67b16e60b73965d30f01ad7/files/types/iarna__toml/index.d.ts?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x54f532a8afd9f620:1

**Comment by asger-semmle** [comment]
Hi ajafff,

Thanks for the bug report.

This was fixed in https://github.com/Semmle/ql/pull/32. It hasn't gone live on lgtm.com yet, but it will soon and then the false positive should go away.

**Comment by xiemaisi** [comment]
The new distribution has just been deployed, and the alert is gone: https://lgtm.com/projects/g/DefinitelyTyped/DefinitelyTyped/latest/files/types/iarna__toml/index.d.ts?sort=name&dir=ASC&mode=heatmap&showExcluded=true#L10.
