### ISSUE TITLE
C/++: False positive - Unused static function

### ISSUE THREAD

**Issue by olehermanse** [Semmle/ql#1283]
**Alert:**

https://lgtm.com/projects/g/cfengine/core/snapshot/4c539ec1d5521407a966fba34c93bb46d05d9895/files/libpromises/crypto.c?sort=name&dir=ASC&mode=heatmap#x35477c73e102d2eb:1

This function is used as a callback, passed as function pointer within the same file.

**Comment by geoffw0** [comment]
Thanks, I'll look into this.

**Comment by geoffw0** [comment]
Hi,

I believe the alert is correct.  `OpenSSLLock_callback` appears to be referenced as a callback in a call to `CRYPTO_set_locking_callback`, but this is in fact a macro invocation and the macro has been defined as nothing.  Thus, `OpenSSLLock_callback` is unreachable.

Let me know if you still have any questions or concerns.

**Comment by olehermanse** [comment]
@geoffw0 Thanks for the investigation! It looks like it's a no-op in the newer versions (running in LGTM) only, so we will probably add some `#if` guards for this.

**Comment by geoffw0** [comment]
Sounds good to me.
