### ISSUE TITLE
Missing note or doc on how to build QL locally, run, test and extend

### ISSUE THREAD

**Issue by rajiff** [Semmle/ql#1333]
Hi

was not able to figure out how to build the QL and trying it locally

I am trying to extending QL for some more language semantics for JavaScript and JAVA

Can we please have such a note documented or instructions be shared

**Comment by xcorail** [comment]
Hi @rajiff
 
Have you already checked the [QL for eclipse](https://help.semmle.com/ql-for-eclipse/Content/WebHelp/home-page.html) plugin? It's a free plugin for Eclipse, that you can use for writing QL queries, and execute them locally.

Please check it out. And as this is not an issue with a query itself, I encourage you to continue this discussion on our [forum](https://discuss.lgtm.com/).

Best

**Comment by samlanning** [comment]
Closing. As mentioned, this would be better discussed on our forum.
