### ISSUE TITLE
CPP: Uninialized variable reported after while loop which always runs at least once

### ISSUE THREAD

**Issue by vpodzime** [Semmle/ql#1350]
In our code we have this:

```
    bool connected = false;
    bool should_retry = true;
    int remaining_tries = MAX_CONNECT_RETRIES;
    int ret;
    while (!connected && should_retry)
    {
        ret = SSL_connect(conn_info->ssl);
        ...
    }
    if (!connected)
    {
        TLSLogError(conn_info->ssl, LOG_LEVEL_ERR,
                    "Failed to establish TLS connection", ret);
        ...
```
and the use of `ret` is reported as potentially using an uninitialized variable [1]. Which I believe cannot happen because the condition in `while()` is always going to be `true` at least the first time and thus the variable `ret` will get initialized.

[1] https://lgtm.com/projects/g/cfengine/core/rev/pr-8b1d1654c2026687e81b86d5d27cd081a3060ab5#1320885514

**Comment by vpodzime** [comment]
Since the two variables in the `while` condition are actually initialized to constants, I would expect this to not report and alert.

**Comment by geoffw0** [comment]
Hi, thanks for this report, I'll take a look and figure out what's going on.

**Comment by geoffw0** [comment]
We've identified the problem as an issue in our logic handling loop entry, a fix is being worked on.

**Comment by geoffw0** [comment]
The fix has been merged and should reach LGTM within about two weeks.  Sorry for taking a while on this one.

**Comment by vpodzime** [comment]
No problem, thanks for fixing the issue!

**Comment by jbj** [comment]
LGTM has been upgraded, and it looks like the alert is gone.
