### ISSUE TITLE
Python: location of py/iter-returns-non-iterator can be confusing

### ISSUE THREAD

**Issue by s0** [Semmle/ql#1427]
See https://discuss.lgtm.com/t/python-false-positive-the-iter-method-of-iterable-class-xxx-does-not-return-an-iterator/2116

In the case where `__iter__` returns an instance of a class that *partially* implements an iterator (e.g. implements `__next__` but not `__iter__`), then the alert location and message can be confusing, as the problem actually lies with the definition of the iterator, and not the use of it.

As a suggested improvement, when returning an instance of a class that implements `__next__` but not `__iter__`, the alert location should instead be the iterator class, and the message something like "This class is returned as an iterator {here}, but is missing a definition for `__next__`, so does not fully implement the iterator interface."

**Comment by webknjaz** [comment]
Not sure how relevant this is _here_ but this check may also need to take into account the fact that projects can have hybrid Python support, meaning that the code is written in a subset of Python which both Python 2 and Python 3 can interpret perfectly.
In such a case, an iterator can implement one of `__next__` or `next` but not both which can make this check flaky as it'd work only under one of Python branches and the linter can miss it if it'd guess the wrong branch...
