### ISSUE TITLE
Python: False Positive in py/procedure-return-value-used

### ISSUE THREAD

**Issue by samlanning** [Semmle/ql#1443]
As reported here: https://discuss.lgtm.com/t/python-false-positive-the-result-of-coroutine-name-is-used-even-though-it-is-always-none/2135

It seems as though [this usage](https://lgtm.com/projects/g/sanitizers/octomachinery/snapshot/85c7c86be4f009fccb14fca62ac8d9704c8d01de/files/octomachinery/app/server/runner.py?sort=name&dir=ASC&mode=heatmap#L64) for some reason does not detect that [`run_forever`](https://lgtm.com/projects/g/sanitizers/octomachinery/snapshot/85c7c86be4f009fccb14fca62ac8d9704c8d01de/files/octomachinery/app/server/machinery.py#L41) is async, and hence not a procedure.

cc @markshannon @taus-semmle

**Comment by markshannon** [comment]
Fixed
