### ISSUE TITLE
Python FP: obj parameter is a supported parameter name when decorated

### ISSUE THREAD

**Issue by imsolost** [Semmle/ql#1506]
Obj as parameter name is a supported parameter name when  wrapped in an @click.group decorator.

See [forum post issue](https://discuss.lgtm.com/t/false-positive-python-click-cli-named-argument-obj/2160)

[Link to error on LGTM](https://lgtm.com/projects/g/Yubico/yubikey-manager/snapshot/f73dda2b16d50f5186b8fa4ed4ee90d5ce7d3743/files/ykman/cli/__main__.py?sort=name&dir=ASC&mode=heatmap#xe35775b0470c912:1)

**Comment by emlun** [comment]
The same probably goes for `@click.command` as well, but I haven't looked as closely at that case.
