### ISSUE TITLE
Java: False positive double checked locking

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [Semmle/ql#1595]
It seems that lgtm is showing a false positive for double checked locking:
https://lgtm.com/projects/g/micronaut-projects/micronaut-core/snapshot/4975e85649c04fa1bda488456cb1f26e19e01afd/files/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java?sort=name&dir=ASC&mode=heatmap#x9ad3d6b82ea0bc8a:1

The code is using local variable to protect consistency as described in
https://wiki.sei.cmu.edu/confluence/display/java/LCK10-J.+Use+a+correct+form+of+the+double-checked+locking+idiom

last example - Compliant Solution (Immutable)

**Comment by aschackmull** [comment]
This is actually a true positive as there is no guarantee that the constructed object is completely immutable. This is one of the really tricky cases where the synchronization is in fact insufficient to establish a proper happens-before relationship, but can be saved by the semantics of final fields. It is true that this case will never be a problem if the `beanContext.getBean(beanType, qualifier)` only ever returns objects for which all fields are declared `final`, but it is not clear from the code whether that's the true, so for that reason it should be considered a true positive.

This is consistent with the reference you give (although it could have been spelled out more clearly). If you read from the start of the noncompliant example (second to last - "Noncompliant Code Example (Immutable)") the text describes the semantics of having all-final fields in which case having only a single racy read can provide a correct implementation (which is the last example as you point out).

I can recommend reading some of the blog posts of Aleksey Shipilëv - he is one of the sources cited in the CMU reference you give, and he describes the java memory model really well, see e.g. the references in the [query help](https://lgtm.com/rules/1507082716110/).

**Comment by KrzysztofKowalczyk** [comment]
Interesting, thank you for insight.
