### ISSUE TITLE
Inconsistent naming of stripParens and getProperExpr

### ISSUE THREAD

**Issue by s0** [Semmle/ql#1863]
The Java and JavaScript ql libraries have inconsistent naming for `Expr` member predicates that effectively do the same thing:

JavaScript: **`stripParens`**
https://github.com/Semmle/ql/blob/742c9708a9888c59391b49041ebb2f18ef2e1ffb/javascript/ql/src/semmle/javascript/Expr.qll#L83

Java: **`getProperExpr`**
https://github.com/Semmle/ql/blob/9012c3240f347655f859aa006817ff008b40aaf9/java/ql/src/semmle/code/java/Expr.qll#L50

I feel that we should unify the naming here, and deprecate whichever one we choose to no longer use, as this caused me some confusion when i was trying to find the Java version of this. IMO `stripParens` is a somewhat more obvious and intuitive name.

**Comment by aschackmull** [comment]
I've been considering changing the java extractor to model parentheses as a predicate that may hold for a given expression instead of manifesting them as actual AST elements.  This would remove the need for the `getProperExpr` predicate, and instead expose the information as an `isParenthesized()` predicate on `Expr`.

**Comment by s0** [comment]
That sounds sensible for me, as it's a step that can be easily forgotten, and doesn't change the semantics. This would lose us some information though in the case where there is unnecessary nesting of parentheses (e.g. `((expr))`). Would it make sense to model this as an integer that represents how many times an expression is directly wrapped in parentheses, and isParenthesized() would just check for a value `> 0`?

**Comment by aschackmull** [comment]
Yes, we might as well keep information about number of parentheses in case someone wants to query for that.  Then the only information that we discard is the location information of the parentheses, but that's probably fine.

**Comment by s0** [comment]
SGTM

**Comment by aschackmull** [comment]
Parentheses are now no longer part of the AST.
