### ISSUE TITLE
LGTM.com - false positive in js/incomplete-hostname-regexp

### ISSUE THREAD

**Issue by sebastian-meyer** [Semmle/ql#1921]
LGTM reports a problem with `js/incomplete-hostname-regexp` where it complains about an unescaped "." in an URL, which in fact is properly escaped.

https://lgtm.com/projects/g/kitodo/kitodo-presentation/snapshot/6791df88b58ce4783e285de9616f47f3ba03f210/files/Resources/Public/Javascript/PageView/Utility.js?sort=name&dir=ASC&mode=heatmap#xa4be3cc3a211c3a5:1

**Comment by esben-semmle** [comment]
This is a true positive, but for a tricky reason. The backslashes in the regular expression string are actually ignored by the JavaScript runtime before the call to `new RegExp`, an additional backslash is needed before each backslash in that string. Alternatively, a regular expression literal could be used instead, in which case the backslash escapes are correct.

Try pasting the following in a console, it shows that the string is equal to a similar string without any backslashes:

```js
var withBackslashes =   '^https?\:\/\/library\.stanford\.edu\/iiif\/image-api\/(1\.1\/)?compliance\.html#level[0-2]$';
var withoutBackslashes= '^https?\:\/\/library.stanford.edu/iiif/image-api/(1.1/)?compliance\.html#level[0-2]$';
withBackslashes === withoutBackslashes;
```

**Comment by sebastian-meyer** [comment]
Thanks for the clarification!
