### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by kamadorueda** [Semmle/ql#1932]
**Description of the false positive**

boolean variable is set to True some lines later in the code

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/fluidattacks/asserts/snapshot/963bae93ab55c0431ce060fc27ade372de387f99/files/fluidasserts/proto/tcp.py#x7882dd7988837adc:1

**Comment by kamadorueda** [comment]
Happens here too

https://lgtm.com/projects/g/fluidattacks/asserts/snapshot/963bae93ab55c0431ce060fc27ade372de387f99/files/fluidasserts/proto/tcp.py?sort=name&dir=ASC&mode=heatmap#x9b459560f141c5b:1

**Comment by tausbn** [comment]
A fix for these false positives has been deployed to LGTM.com, and so I'm closing this issue.
