### ISSUE TITLE
LGTM.com - false positive - JavaScript - Missing rate limiting

### ISSUE THREAD

**Issue by GenneratorX** [Semmle/ql#1949]
**Route Handler performs authorization, but is not rate-limited.**

I'm using **rate-limiter-flexible** package for rate limiting in my NodeJs/Express website. I'm using the rate limiter middleware like this:
```typescript
const rateLimiter = (req, res, next) => {
  // rate limiter logic here
}

app.post('/loginUser', rateLimiter, function(req, res) {
  // app logic here
}
```
And it works just fine (the **rateLimiter** middleware function is always executed before the app logic). In Express you can chain as many middleware functions in this manner.

**URL:**
https://lgtm.com/projects/g/GenneratorX/my-website/snapshot/4032b89b7b7c0a218aea347f0395243aae59cc2c/files/src/app.ts#xfebca4f77d6910da:1

**Comment by xiemaisi** [comment]
Thanks for your report, @GenneratorX! You are absolutely right, we shouldn't flag that. I'll look into getting it fixed.

**Comment by xiemaisi** [comment]
Fix has been merged, and should be deployed on LGTM.com soon. Thanks again for your report!
