### ISSUE TITLE
LGTM.com - false positive for bitfield signedness when using make_signed

### ISSUE THREAD

**Issue by VeaaC** [Semmle/ql#1964]
In https://github.com/heremaps/flatdata/blob/master/flatdata-cpp/include/flatdata/internal/BitHelpers.h is a functions that is used to sign-extend an integer. It uses bitfield to do so:
``` cpp
template < typename ResultType, int num_bits, typename T >
typename std::enable_if< IsSigned< ResultType >::value, ResultType >::type
extend_sign( T value )
{
    static_assert( std::is_unsigned< T >::value, "expected unsigned type" );
    struct
    {
        typename std::make_signed< T >::type x : num_bits;  // use the compiler to sign extend bits
    } temp_struct;
    temp_struct.x = value;
    return static_cast< ResultType >( temp_struct.x );
}
```
Even though the bitfield is explicitly signed, it triggers the warning `Ambiguously signed bit-field member`

https://lgtm.com/projects/g/heremaps/flatdata/snapshot/0d62e072f3a06b93a814014c672751413f52c3f8/files/flatdata-cpp/include/flatdata/internal/BitHelpers.h?sort=name&dir=ASC&mode=heatmap#x603e0a5b2ac48099:1

**Comment by jbj** [comment]
Thank you for the report. It turns out this alert is attached to the uninstantiated template, where the type is not known. I'll open a PR with a fix to ignore uninstantiated templates.

**Comment by jbj** [comment]
The fix has been merged, and it will take effect the next time we deploy new queries to lgtm.com. That should happen within a few weeks from now.
