### ISSUE TITLE
LGTM.com - false positive Format expects 2 arguments but given 1

### ISSUE THREAD

**Issue by kallisti5** [Semmle/ql#1970]
**Description of the false positive**

Two args, two format items.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/headers/private/file_systems/QueryParser.h#x37242992c01d5a0a:1

**Comment by samlanning** [comment]
Duplicated in #1971
