### ISSUE TITLE
LGTM.com - false positive - Format expects 2 arguments but given 1

### ISSUE THREAD

**Issue by kallisti5** [Semmle/ql#1971]
**Description of the false positive**

Format expects 2 arguments but given 1

Seems to be missing __func__ as an argument?

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/btCoreData/BTCoreData.cpp?sort=name&dir=ASC&mode=heatmap#x84553362d74646aa:1

**Comment by kallisti5** [comment]
also
https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/btCoreData/ChannelInterface.cpp#xf0961682136884f7:1

**Comment by kallisti5** [comment]
also
https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/hci/acl.cpp#xba333aeaedca5123:1

**Comment by kallisti5** [comment]
also
https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/hci/acl.cpp#x82dacf0a4f0ec54d:1

**Comment by kallisti5** [comment]
also
https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/hci/acl.cpp#x15778d816ea76adc:1

**Comment by kallisti5** [comment]
also
https://lgtm.com/projects/g/haiku/haiku/snapshot/d26be28c9c1882a2fe59ca80fbcf9410053b590f/files/src/add-ons/kernel/bluetooth/hci/bluetooth.cpp#x7349db345b1eed06:1

**Comment by geoffw0** [comment]
I believe all of these will be fixed by https://github.com/Semmle/ql/pull/1987 (please allow approximately 2 weeks for the changes to reach LGTM).
