### ISSUE TITLE
LGTM.com - false positive  C# Potentially dangerous use of non-short-circuit logic

### ISSUE THREAD

**Issue by jbtule** [Semmle/ql#1972]
**Description of the false positive**

> The & and | operators do not use short-circuit evaluation and can be dangerous when applied to boolean operands. In particular, their use can result in errors if the left-hand operand checks for cases in which it is not safe to evaluate the right-hand one.

However, safety of the right operand is determinable, and is not checked in this test.

> The | and & logical operators, known as non-short circuit operators, should not be used. Using a non-short circuit operator reduces the efficiency of the program, is potentially confusing and can even lead to the program crashing if the first operand acts as a safety check for the second.

Program efficiency can also reduce security, such as if you are trying to do constant time comparisons, to reduce the information of timing oracles of code that deals with sensitive data.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/jbtule/keyczar-dotnet/snapshot/5b0a3951b2f83d6049f61b4effc65b1126f773cf/files/Keyczar/Keyczar/Util/Secure.cs?sort=name&dir=ASC&mode=heatmap#xf45850b7a250a084:1

**Comment by calumgrant** [comment]
Hi Jay, Many thanks for your report.

You are right that the query did not consider the timing implications, or the fact that `MethodImpl(MethodImplOptions.NoOptimization)` was used on the method.

It's very hard for a query to automatically determine the reason for the non-short-circuit in this particular case. In the general case, you'd probably prefer `||` where efficiency is more important than preventing timing information leaks.

One solution for now is to use an alert suppression comment to remove the alert on that line, which is described [here](https://help.semmle.com/lgtm-enterprise/user/help/alert-suppression.html#c).
