### ISSUE TITLE
LGTM.com - false positive C# "Variable may be null here because of this assignment."

### ISSUE THREAD

**Issue by jbtule** [Semmle/ql#1973]
**Description of the false positive**

> Variable _converter_ may be null here because of this assignment.

As you can see, it may not:

``if (converter != null && converter.CanConvertFrom(target.GetType()))``

my guess is that it's getting confused because _converter_ is of type `dynamic`

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/ekonbenefits/dynamitey/snapshot/32d21b116695780312da079f180861c8195c3944/files/Dynamitey/Dynamic.cs?sort=name&dir=ASC&mode=heatmap#xa08047fab3f00bc8:1

**Comment by AlexTereshenkov** [comment]
@calumgrant

**Comment by hvitved** [comment]
Thank you very much for reporting this.

You are right that the reason this is flagged is because we do not currently handle dynamic calls to operators, such as `converter != null` above. I will open a PR to fix this shortly.

**Comment by hvitved** [comment]
Fixed on https://github.com/Semmle/ql/pull/1982.
