### ISSUE TITLE
LGTM.com - false positive c# This assignment to is useless, since its value is never read.

### ISSUE THREAD

**Issue by jbtule** [Semmle/ql#1974]
**Description of the false positive**

The variable is clearly used, I think it's probably confused because of the type `dynamic`

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/ekonbenefits/dynamitey/snapshot/32d21b116695780312da079f180861c8195c3944/files/Dynamitey/Internal/Optimization/InvokeHelper.cs?sort=name&dir=ASC&mode=heatmap#x819805487acb5956:1

**Comment by calumgrant** [comment]
Thank you for your report, we appreciate it.

I can confirm this is a false-positive, and we're working on a fix.

**Comment by calumgrant** [comment]
The bug actually lies in the way we compute the control-flow graph. We didn't consider the cases after the `default:` to be reachable, but actually they are.

**Comment by AlexTereshenkov** [comment]
The fix submitted by @calumgrant should eradicate the false positive you've filed. Please let us know if the problem persists. Thanks!
