### ISSUE TITLE
LGTM.com - false positive: argument should be of type ... but is of type 'unknown'

### ISSUE THREAD

**Issue by wojdyr** [Semmle/ql#1975]
**Description of the false positive**
Language: C++.
Query: Wrong type of arguments to formatting function

In a template, I get:

    This argument should be of type 'int' but is of type 'unknown'

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/project-gemmi/gemmi/snapshot/f526c519b18b6434dd5025bef97c5fcd057d9f63/files/src/map.cpp#xe9e63eaf9558ecc3:1

(I just learned about LGTM and already found one bug using it. Thanks a lot!)

**Comment by nickrolfe** [comment]
Thanks for the report! The alert is attached to the uninstantiated template, where the type is unknown. I've opened a PR (#1979) to fix this. Once it's been merged, it will take effect the next time we deploy new queries to lgtm.com. That should happen within a couple of weeks.
