### ISSUE TITLE
LGTM.com - false positive Python 3.6: f-string with a tuple inside braces show the SyntaxError.

### ISSUE THREAD

**Issue by denis-trofimov** [Semmle/ql#1990]
**Description of the false positive**

Python 3.6: f-string with a tuple inside braces show the SyntaxError.

It is valid and tested in pytest 
```py
f"({shape[0], shape[1]}), ({shape[2], shape[3]})" 
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/adb05a7df87d9b1f8518d7bc1d19db4f2f98d3d9/files/matrix/matrix_operation.py?sort=name&dir=ASC&mode=heatmap#x7b42a1e228ab0aad:1

**Comment by tausbn** [comment]
A fix for this has been created, and it should hopefully go live within the next few weeks. I will close this issue at that point.
