### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by eamodio** [Semmle/ql#1991]
**Description of the false positive**

`Git.apply` here is calling a static function, not calling the built-in `apply`.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/eamodio/vscode-gitlens/snapshot/0119be24d14a664ae5b9807df5f0d1d367badbda/files/src/git/gitService.ts?sort=name&dir=ASC&mode=heatmap#xf59607030876bf5:1

**Comment by xiemaisi** [comment]
Thank you for reporting this, @eamodio! I've put up a fix (https://github.com/Semmle/ql/pull/1996).
