### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by olivier-spinelli** [Semmle/ql#1993]
**Description of the false positive**

The IDisposable object is NOT disposed... That I agree... BUT the variable is a static one. The life time of the object is the one of the AppDomain: should we expect a subscribtion to the AppDomain.Unload and dispose it here? I don't think so: up to me, with a static field, there should be no warn... 

**https://lgtm.com/projects/g/Invenietis/CK-Monitoring/snapshot/16b34d16b8ab65db6f0b07d0b0c7cd2e221597be/files/CodeCakeBuilder/dotnet/Build.NuGetHelper.cs?sort=name&dir=ASC&mode=heatmap#x37b2c38f4c25e629:1**

**Comment by hvitved** [comment]
Thank you for reporting this. I am not familiar with the particular nuget API, but it looks like `WithRefreshCacheTrue` [does not return `this`]( https://github.com/NuGet/NuGet.Client/blob/f5916a527c442f896f787c593252b37a345da835/src/NuGet.Core/NuGet.Protocol/SourceCacheContext.cs#L146), i.e. use a fluent API, so the `new SourceCacheContext()` object will not actually be assigned to the static field `_sourceCache`, but rather a cloned object, so it looks like a true positive to me.

That being said, I realized that the query does not actually handle fluent APIs, which I will fix.

**Comment by olivier-spinelli** [comment]
Glad to help (and an advice: don't spend too mush time on NuGet API, it's en ever changing world full of stange things - to be polite).
