### ISSUE TITLE
 Python: LGTM.com - false positive

### ISSUE THREAD

**Issue by L1ghtn1ng** [Semmle/ql#1995]
LGTM suggest that this code is an unreadable statement but this is not the case

https://lgtm.com/projects/g/laramies/theHarvester/alerts/?mode=tree&ruleFocus=3980095

This project is a python3.6+ project

**Comment by samlanning** [comment]
Hi @L1ghtn1ng,

The alert specifies that the code is *unreachable* not *unreadable*, meaning that it will never be executed. This is because `recursion` is assigned `None` on line `591`, so `if recursion` will always be false.

As a result, I don't think that this is a false positive.

**Comment by AlexTereshenkov** [comment]
@L1ghtn1ng as @s0 has pointed out, this is a valid alert and not a false positive hence I close this issue. Feel free to post any questions you may have on our [forums](https://discuss.lgtm.com/) or if you think you've found a false positive, create an [issue](https://github.com/Semmle/ql/issues/new/choose) here on GitHub.
