### ISSUE TITLE
LGTM.com - C++ false positive in boost::spirit

### ISSUE THREAD

**Issue by vmatare** [Semmle/ql#2007]
**Description of the false positive**
`boost::spirit` overloads all kinds of C++ operators to create a BNF-like C++ syntax. Normal C++ operator coding guidelines don't apply here.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/MASKOR/gologpp/snapshot/9881c1de021f74ac5170c7fb3f42279338846253/files/src/parser/action.cpp?sort=name&dir=ASC&mode=heatmap#x2c2a1c518d75536:1
Another one:
https://lgtm.com/projects/g/MASKOR/gologpp/snapshot/9881c1de021f74ac5170c7fb3f42279338846253/files/src/parser/effect_axiom.cpp?sort=name&dir=ASC&mode=heatmap#xe26b25d5fbd67bf9:1

**Comment by geoffw0** [comment]
Thanks for this report, a fix for it is in progress.

**Comment by geoffw0** [comment]
The fix (https://github.com/Semmle/ql/pull/2035) has been merged and should reach LGTM within about two weeks.

**Comment by jbj** [comment]
There are no alerts on https://lgtm.com/projects/g/MASKOR/gologpp/alerts, so it looks like the fix worked.
