### ISSUE TITLE
C++17 problem

### ISSUE THREAD

**Issue by patrickelectric** [Semmle/ql#2010]
It appears that lgtm is failing with C++17 projects: https://lgtm.com/projects/g/bluerobotics/ping-viewer/logs/languages/lang:cpp
Ping-viewer uses C++17: https://github.com/bluerobotics/ping-viewer/blob/master/pingviewer.pro#L9
Somehow it appears to be using C++14 from this line in lgtm: `[2019-09-24 08:04:33] [build] Project MESSAGE: Compiler:      __cplusplus=201402L __GNUC__=8 __GNUC_MINOR__=3 __GNUC_PATCHLEVEL__=0`

Any idea ?

**Comment by patrickelectric** [comment]
It appears that the Qt version is a bit old in the lgtm server, C++17 needs at least Qt 5.12+ LTS.
Is it possible to specify or install/update to use a newer Qt version ?

**Comment by jbj** [comment]
I'm planning to upgrade our build environment to Ubuntu 19.10 when it's released later this month. That should fix it.

**Comment by patrickelectric** [comment]
Thanks, looking forward to it!

**Comment by patrickelectric** [comment]
@jbj any update ?

**Comment by jbj** [comment]
We're testing the update now, but it will likely have to go through a few more cycles of change and test before we can put it in production. Because we're upgrading the environment for all languages at once, it's not only C/C++ that has to work.

Thank you for your patience so far.

**Comment by patrickelectric** [comment]
@jbj any update ?

**Comment by jbj** [comment]
Yes! We deployed the Ubuntu 19.10 images two days ago. Is it working now?

**Comment by patrickelectric** [comment]
Yep it's!

**Comment by pavelkryukov** [comment]
Hi! Could you please tell if there are plans to deploy Ubuntu 20.04 or later so GCC 10 may be supported, which includes C++20?

**Comment by jbj** [comment]
At the moment we're focusing on [Code Scanning](https://github.blog/2020-09-30-code-scanning-is-now-available/), which can analyse the code with the same underlying technology as LGTM but has a more flexible build environment.
