### ISSUE TITLE
LGTM.com - false positive C# This assignment to is useless, since its value is never read.

### ISSUE THREAD

**Issue by jbtule** [Semmle/ql#2018]
**Description of the false positive**

Thinks the variable `count` is not ever read, but it's used in a closure from c# 7 local function.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/jbtule/keyczar-dotnet/snapshot/6f9f609b2390cbb65220aea7d9cbbdd94df2179c/files/Keyczar/KeyczarTest/Support/Util.cs?sort=name&dir=ASC&mode=heatmap#x27914cbe517e7519:1

**Comment by hvitved** [comment]
Thank you very much for reporting this. I agree that this is a false positive.

**Comment by hvitved** [comment]
This issue has now been fixed, thanks again for your report.
