### ISSUE TITLE
LGTM.com - false positive TypeScript

### ISSUE THREAD

**Issue by L2jLiga** [Semmle/ql#2020]
**Description of the false positive**
It's converter to SVG path for rectangles

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/L2jLiga/xd2svg/snapshot/32359fb7e5082e1c95ff732fbb6001b6b03addcb/files/src/converter/core/utils/svg-rect-to-clip-path.ts#x46b090d56a8827a2:1

**Comment by AlexTereshenkov** [comment]
@esben-semmle while this [rule](https://lgtm.com/rules/1928560207/) is definitely useful to spot missing spaces in string concatenation (as in `"Data is saved" + "at home folder"`), perhaps we could set a threshold for a minimal string length to apply this alert to? Then we could skip string concatenation which is not intended to be a human readable text such as `"y" + "=x" + "50"`.

**Comment by AlexTereshenkov** [comment]
@L2jLiga Thanks for reporting this. It does look like in this particular case raising an alert on concatenating strings where the final output is not supposed to be read by a human is not very helpful. Let us look into the problem and will see what can be done to improve the current query.
