### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by phax** [Semmle/ql#2026]
Hi,
next try with a false positive in Java code:

```java
  public static String replaceMultiple (@Nullable final String sInputString,
                                        @Nullable final String [] aSearchTexts,
                                        @Nullable final String [] aReplacementTexts)
  {
    if (hasNoText (sInputString))
      return sInputString;

    final int nSearchTextLength = aSearchTexts == null ? 0 : aSearchTexts.length;
    final int nReplacementTextLength = aReplacementTexts == null ? 0 : aReplacementTexts.length;
    if (nSearchTextLength != nReplacementTextLength)
      throw new IllegalArgumentException ("Array length mismatch!");

    // Nothing to replace?
    if (nSearchTextLength == 0)
      return sInputString;

    String sOutput = sInputString;
    for (int nIndex = 0; nIndex < nSearchTextLength; ++nIndex)
      sOutput = replaceAll (sOutput, aSearchTexts[nIndex], aReplacementTexts[nIndex]);
//                                                         ^ Variable aReplacementTexts may be null here as suggested by this null guard.
    return sOutput;
  }
```

It is indeed a bit indirect, but:
* if `aReplacementTexts` is `null`, `nReplacementTextLength` becomes 0.
* `if (nSearchTextLength != nReplacementTextLength)` ensures both values are identical
* Therefore for `if (nSearchTextLength == 0)` it can be deduced that `nReplacementTextLength` is also `0`.
* Ergo, if pass that `if` it is ensured, that `aReplacementTexts` is not `null`

Link to issue:

https://lgtm.com/projects/g/phax/ph-commons/snapshot/68e033c0185feb3860a1fd5341692bc166db83f7/files/ph-commons/src/main/java/com/helger/commons/string/StringHelper.java?sort=name&dir=ASC&mode=heatmap#x5af3a4e7deafdb76:1

Thanks and hth, Philip

**Comment by aschackmull** [comment]
Thank you for your report.  I've opened the PR #2036 to fix this case.  Most of the logic was already in place, we just needed to carry inferred conclusions about `nSearchTextLength` over to `nReplacementTextLength`.
