### ISSUE TITLE
LGTM.com - My Project make crash in an infinite loop the whole infrastructure

### ISSUE THREAD

**Issue by Milerius** [Semmle/ql#2050]
**Description of the false positive**

as discussed on the forum: https://discuss.lgtm.com/t/why-my-project-always-timeout/2301

**URL to the alert on the project page on LGTM.com**

There is no alert, because the analysis is crashing.

(It's will be easier for me to follow the update regarding this issue here, that's why i open the issue here)

**Comment by s0** [comment]
Hi @Milerius,

I have just responded to the forum thread.

Cheers,
Sam.
