### ISSUE TITLE
LGTM.com - false positive - TypeScript

### ISSUE THREAD

**Issue by AlexTereshenkov** [Semmle/ql#2051]
**Description of the false positive**

`Useless assignment to local variable` alert is raised as part of the `import` statement.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/kyranet/Skyra/snapshot/0e406afb893eb5bc2aca7afca3177a7f68f6bc6e/files/src/tasks/reminder.ts?sort=name&dir=ASC&mode=heatmap

Maybe related to a previous [issue](https://discuss.lgtm.com/t/solved-typescript-false-positive-unused-import/1771). The issue may have been fixed with https://github.com/Semmle/ql/pull/1076.

**Comment by esben-semmle** [comment]
It looks like we have a problem with nameless TypeScript classes (off by one, perhaps?).
`js/useless-assignment-to-local` flags `C2` in the following code when it is in a file with `.ts` extension, but not when the file has a `.js` extension:

```
var C1 = global.C1;
var C2 = global.C2;

class C extends C1 {}
export default class extends C2 {}
```
See https://git.semmle.com/esben/ql/commit/2dfd0f98fc316e8ced6e5e8010eae35cd54f7bcf

**Comment by erik-krogh** [comment]
It seems to be related to SSA/BasicBlocks. 

The following simple query returns a different result for the `.js` vs. the `.ts` file from above. 

```
from SsaSourceVariable v, ReachableBasicBlock bb, VarUse u
where v = u.getVariable() and bb.getANode() = u
select v
```

Interrestingly, replacing `ReachableBasicBlock` with `BasicBlock` and the results are the same for both files. 

I'll debug some more tomorrow.

**Comment by asger-semmle** [comment]
The root cause of this kind of issue is almost always in the extractor, since the everything in the QL layer is shared between JS and TS.

Looking at the AST in astexplorer.net, it seems the class expression is represented as a `ClassDeclaration` in the TypeScript AST, and we don't convert it correctly in TypeScriptASTConverter.

**Comment by erik-krogh** [comment]
> Looking at the AST in astexplorer.net, it seems the class expression is represented as a `ClassDeclaration` in the TypeScript AST, and we don't convert it correctly in TypeScriptASTConverter.

You're right. The JavaScript extractor produces a `ClassExpr` while the TypeScript extractor produces a `ClassDeclStmt` for the `class extends C2 {}` expression.

**Comment by kyranet** [comment]
Has this been landed into production yet? I am getting errors tirelessly.

**Comment by xiemaisi** [comment]
No, this fix has not been deployed yet.
