### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by cdsmith** [Semmle/ql#2052]
**Description of the false positive**

LGTM complains of an XSS vulnerability due to including user input in a URL.  However, I believe the use of `encodeURIComponent` should address this.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/google/codeworld/snapshot/8e78087205b2168e4340416885464b313cf25767/files/web/run.html?sort=name&dir=ASC&mode=heatmap#xeb91aa024ab0c6af:1

**Comment by esben-semmle** [comment]
Thank you for reporting this, @cdsmith. You are right that this is a false positive.
I will put up a fix soon.

**Comment by asger-semmle** [comment]
The FP should be fixed by https://github.com/Semmle/ql/pull/2216.
