### ISSUE TITLE
LGTM.com - false positive for Java Integer Overflow checking

### ISSUE THREAD

**Issue by shemnon** [Semmle/ql#2059]
**Description of the false positive**

The "Test is always true" test is not always true.  In the cast tagged we are checking for integer overflow by asserting the added number is greater than the base.  If it overflowed then it would be a negative number or less than the comparison at least.

https://lgtm.com/projects/g/hyperledger/besu/snapshot/3bb5acb1890828050404cc559ce9566c60b10668/files/besu/src/main/java/org/hyperledger/besu/controller/GasLimitCalculator.java?sort=name&dir=ASC&mode=heatmap#x9b655ea69b225cef:1

A similar alert in the same file for underflow 8 lines below.

IMHO the check should be a different check when math is involved and it is detected as an overflow check pattern.  An error should still be raised but instead of saying it's a useless comparison the recommendation should be to recommend `java.lang.Math#addExact` and friends instead of relying on auto overflow and underflow.  It reads better and communicated the intent more clearly.

**Comment by aschackmull** [comment]
Thank you for your report. I've opened a PR (#2085) to fix this.
