### ISSUE TITLE
LGTM.com - false positive for nonlocal variables access/visibility

### ISSUE THREAD

**Issue by maxfischer2781** [Semmle/ql#2060]
**Description of the false positive**

These are several reports that all boil down to the same cause: An outer variable that is modified as a ``nonlocal`` in an inner function seems to be analysed as *several separate* variables. However, ``nonlocal`` means the inner variable is a writeable closure and thus "both" variables are actually just a single one.

This is visible in the two reports linked below:

* The inner assignment is reported as unused, even though it is used in the outer scope.
* The outer assignment is assumed to be a constant, even though it is mutated in the inner scope.

Both reports would be fine if it were not for the inner ``nonlocal`` linking the two.

**URL to the alert on the project page on LGTM.com**

*value assigned to local variable is unused* (but used outside as nonlocal variable):
https://lgtm.com/projects/g/MaineKuehn/usim/snapshot/3d254d3788b0ace175b72abf530fe0d9855fbaa3/files/usim_pytest/utility.py?sort=name&dir=ASC&mode=heatmap#x73e5e42514119a62:1

*unreachable statement* because of const-propagation of unassigned local (but assigned as inside nonlocal variable):
https://lgtm.com/projects/g/MaineKuehn/usim/snapshot/3d254d3788b0ace175b72abf530fe0d9855fbaa3/files/usim_pytest/utility.py?sort=name&dir=ASC&mode=heatmap#x406886cfcd8bf272:1

**Comment by tausbn** [comment]
The fix has gone live on LGTM.com, and so I'm closing this issue.
Thanks for the report!
