### ISSUE TITLE
LGTM.com - false positive "Explicit export is not defined"

### ISSUE THREAD

**Issue by chrishkchris** [Semmle/ql#2071]
**Description of the false positive**
I think there is a false positive on "Explicit export is not defined"
I have already defined the function but it tells that "the name exported by __all__ is not defined". I tested that the function can be imported outside using import * so I think there should be no problem.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/apache/incubator-singa/snapshot/e42fca51ff4c03b456ceff12974dba64934a86be/files/examples/autograd/xceptionnet.py?sort=name&dir=ASC&mode=heatmap#x7cb181f811af62ad:1

**Comment by madrisan** [comment]
Some issue occurring here:
https://lgtm.com/projects/g/madrisan/pyxymon/?mode=list

**Comment by madrisan** [comment]
Seems not fixed yet. Same issue reported for this code
- GitHub code: https://github.com/madrisan/pyxymon/blob/master/pyxymon.py#L9
- LGTM scan: https://lgtm.com/projects/g/madrisan/pyxymon/alerts/?mode=list&severity=error

but AFAICS it looks like a false-positive (a Python import at command line works as expected).
