### ISSUE TITLE
LGTM.com - alert suppression is not working with syntax error

### ISSUE THREAD

**Issue by cdsmith** [Semmle/ql#2072]
**Description of the false positive**

I've added a comment to suppress this alert, but it's still appearing.  I'm sure that's probably because the parser fails and thus can't find the suppression comment; but I wonder if there is a way to avoid this.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/google/codeworld/snapshot/80f551d20c5d3fbadff381da62c8aca18c9b99ab/files/codeworld-base/jsbits/deep_eq.js?sort=name&dir=ASC&mode=heatmap#x99e921859b73cf8:1

**Comment by esben-semmle** [comment]
You can avoid seeing alerts for the file entirely by configuring the LGTM analysis with [`.lgtm.yml`](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file), you can see a concrete usage [here](https://github.com/ampproject/amphtml/blob/master/.lgtm.yml).
You either want to classify `codeworld-base/jsbits/deep_eq.js` as something like "ignored" (using a `path_classifiers` section), or exclude it from extraction entirely (by using an `extraction` section).

**Comment by asgerf** [comment]
It's unfortunate that syntax errors can't be suppressed by a comment, but I'm going to close the issue as 'wont fix'. Esben's suggestion above is a valid workaround.
