### ISSUE TITLE
LGTM.com - false positive Python Django

### ISSUE THREAD

**Issue by JLLeitschuh** [Semmle/ql#2081]
**Description of the false positive**

https://lgtm.com/projects/g/graphite-project/graphite-web/snapshot/1a8e7ffc2eab2210a73f30b03e9cdeb520a02057/files/webapp/graphite/dashboard/views.py?sort=name&dir=ASC&mode=heatmap#x4e5b57bd3ed08db4:1

I've never actually worked with Django, but I believe that these are false positives because they are using the Django SQL safe methods:

> Django’s querysets are protected from SQL injection since their queries are constructed using query parameterization. A query’s SQL code is defined separately from the query’s parameters. Since parameters may be user-provided and therefore unsafe, they are escaped by the underlying database driver.
>
> Django also gives developers power to write raw queries or execute custom sql. These capabilities should be used sparingly and you should always be careful to properly escape any parameters that the user can control. In addition, you should exercise caution when using extra() and RawSQL.
> \- https://docs.djangoproject.com/en/2.2/topics/security/#sql-injection-protection

**Comment by RasmusWL** [comment]
Thanks for reporting this. It's a false positive alright. We're looking into fix this :blush:
