### ISSUE TITLE
LGTM.com - false positive for unused variable [TypeScript]

### ISSUE THREAD

**Issue by AlCalzone** [Semmle/ql#2091]
**Description of the false positive**
TypeScript: An `import`-ed symbol which is used as an indentifier for a class property is not recognized as used.

**URL to the alert on the project page on LGTM.com**
See https://lgtm.com/projects/g/AlCalzone/node-zwave-js/snapshot/b752986d11840001ee0ebb0b3c4a63b39abd99a1/files/src/lib/commandclass/WakeUpCC.ts?sort=name&dir=ASC&mode=heatmap#xac41bfbe5fa9504:1

`SET_VALUE` is used in line 43.

**Comment by asger-semmle** [comment]
Hi AlCalzone,

Thanks for the bug report. I've found the root cause of the problem and will get a fix up soon.

**Comment by AlCalzone** [comment]
Thanks for the quick fix! Any idea when this is going to be active?

**Comment by asger-semmle** [comment]
It will take a few weeks for the change to land on LGTM.com.
