### ISSUE TITLE
LGTM.com - false positive - This query depends on a user-provided value. [JavaScript]

### ISSUE THREAD

**Issue by Sprax2013** [Semmle/ql#2096]
**Description of the false positive**
I check the contents of the string, making it a false positive. The value ist user-dependence but the value is hardcoded by me.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/Sprax2013/Api.Sprax2013.de/snapshot/73c1fa77626ff15b5820cb5ce6f9e526847bb8fd/files/db-utils/DB_SkinDB.js?sort=name&dir=ASC&mode=heatmap#x89f1f395fe1703e2:1

**Comment by esben-semmle** [comment]
I think your check is wrong, it will let all strings through due to `typeof type !== 'string' && ...`.

```
> let type = 'evil-string'; 
> let invalid = typeof type !== 'string' && type != 'original' && type != 'clean'; 
> console.log(invalid);
false
```

Did you mean to write `type !== 'original' && type !== 'clean'` instead?
```
> let type = 'evil-string'; 
> let invalid = type !== 'original' && type !== 'clean'; 
> console.log(invalid);
true
```

**Comment by Sprax2013** [comment]
You are right >-<

It should have been `typeof type !== 'string' || (type != 'original' && type != 'clean')` but I didn't notice
