### ISSUE TITLE
LGTM.com - false positive - cpp/bitwise-sign-check

### ISSUE THREAD

**Issue by zeux** [Semmle/ql#2120]
This code (with CXn having `int` type):

```
// check if all CXn are non-negative
if ((CX1 | CX2 | CX3) >= 0)
```

Trriggers a false positive "Potential unsafe sign check of a bitwise operation.":

https://lgtm.com/projects/g/zeux/meshoptimizer/snapshot/cb6b998207db4044e90ed097ab9b9d5f28d370cb/files/src/overdrawanalyzer.cpp?sort=name&dir=ASC&mode=heatmap#x2ac8a3bd53cf5210:1

This pattern is safe and important for performance in this specific case. I'm not sure what the motivation is behind this check - the documentation includes an example with `&` which is presumably what a misuse of signed checks looks like in practice, however:

1. This code uses `|`
2. If I needed to check if *any* integers are non-negative I would have needed to use `(CX1 & CX2 & CX3) >= 0)`.

If the desire is to catch issues similar to the issues in documentation I feel like the query should be more refined to recognize the specific pattern `a & (1 << n)` instead of being so general.

**Comment by jbj** [comment]
Thanks for the report.

@geoffw0, this looks related to the problem you fixed in #1605, where the user wrote:
> Your rationale for flagging comparisons > 0 make sense, but explicit comparisons < 0 are, quite obviously, an explicit test of the sign bit itself.

The way I read both of these bug reports is that we should allow checking if a signed bitwise operation is _negative_, but we should not allow checking if it's _positive_. If `e` is a signed bitwise operation, that means these are okay: `e >= 0`, `e < 0`, `0 <= e`, `0 > e`; the four other combinations (`e <= 0`, ...) are not okay. Do you agree?

**Comment by geoffw0** [comment]
Yes, except that I also think that all of the `>=` / `<=` combinations should be OK regardless of their logical meaning.  If someone writes `e <= 0`, that may be logically equivalent to `!(e > 0)` (which we would flag), but by writing `<=` they are signalling that they're already thinking of it as a signed value.

That leaves two cases we want to flag: `e > 0` and `0 < e`.

I've opened a PR https://github.com/Semmle/ql/pull/2122, but I'm open to further discussion on exactly which cases to cover.

**Comment by jbj** [comment]
@zeux Now that #2122 is fixed, you can expect the alert to go away the next time we deploy new queries. That's scheduled to happen in about two weeks from now. Thanks again for filing a bug report and for the detailed reasoning you provided.
