### ISSUE TITLE
Java: Cannot import QLL files with dashes in their name

### ISSUE THREAD

**Issue by cosmin79** [Semmle/ql#2124]
I was trying to import a QLL file e.g. `import Security.CWE.CWE-611.XmlParsers` into a QL file since I wanted to extend the original query where this is used to work for my custom case. This doesn't seem possible however. Could you advise on whether this is a bug / ways to achieve this?

**Comment by AlexTereshenkov** [comment]
Hi @cosmin79 

Thanks for posting this. It is indeed impossible to import a `.qll` library file if it's stored within a folder containing a hyphen (`-`). There is no workaround around that. 

This particular `.qll` file was not originally created to be imported as a library but rather to be used by a `.ql` query stored in the very same folder. The easiest solution would be just to copy this file (or file contents) into a new file within your Eclipse project (I assume you are working with a snapshot in Eclipse?) to import it into your query. If you are using the LGTM query console, you would need to copy the contents of the `import Security.CWE.CWE-611.XmlParsers` file into the query console to make it available.

Please let me know if this works for you and if you have any other concerns.

Cheers

**Comment by cosmin79** [comment]
Hey. Thanks for the answer! In my current setup, I have copied over the `.qll` file content to a different file in my Eclipse project and that works. Do you think it would be reasonable to make those files importable in future versions? In my use case for example, I'm trying to add further predicates for other types of XML parsers by subclassing `XmlParserCall`. In this particular example, I would still want to reuse the existing rules.

**Comment by AlexTereshenkov** [comment]
@cosmin79 glad the workaround with copying the file contents works for you, at least you can progress with that. I do think that it would make more sense to allow those libraries to be imported by custom queries. I've talked to my colleagues and submitted a PR which moves the file into another directory from where it will be importable. It will take up to a few weeks for the fix to land in LGTM.com deployment, so please check in later and let us know if the issue persists. 

Thanks!
