### ISSUE TITLE
LGTM.com - false positive: "Unexpected character" alert for private fields in JavaScript

### ISSUE THREAD

**Issue by Trott** [Semmle/ql#2136]
**Description of the false positive**

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/nodejs/node/snapshot/a63c1448fcfcfddd389bb94e690371bb20e9f840/files/lib/internal/source_map/source_map.js?sort=name&dir=ASC&mode=heatmap#xd5b9c593017fbfa8:1

The alert is for a new-ish ECMAScript syntax for private fields. https://github.com/tc39/proposal-class-fields#private-fields

It is supported unflagged in recent versions of Chrome and a few other browsers, as well as Node.js. 
https://caniuse.com/#search=private%20fields
https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields-private-instance-class-fields-basic-support

**Comment by xiemaisi** [comment]
Thank you for your report, @Trott! We do not support private fields yet, since they are currently only a Stage 3 proposal without an official test suite. We will add support once the proposal advances to Stage 4 or gains a test suite (which usually means that a proposal will advance soon).

**Comment by asgerf** [comment]
Support for private fields landed in https://github.com/Semmle/ql/pull/2715.
