### ISSUE TITLE
LGTM.com - false positive "Non-iterator of class 'DFT' may be used in for-loop" 

### ISSUE THREAD

**Issue by buffer** [Semmle/ql#2137]
**Description of the false positive**

I am reporting three identical issues "Non-iterator of class 'DFT' may be used in for-loop" but these are just three list comprehensions so I think a misclassification is happening here.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/buffer/thug/snapshot/1d05983b4aa4099a82d8e5c516ee4430f23b2f1b/files/thug/DOM/DFT.py?sort=name&dir=ASC&mode=heatmap#xbe8beebd0188734a:1

**Comment by AlexTereshenkov** [comment]
@buffer thanks for reporting this! 

It does look as the analyzer is confused when the iteration happens in the body of a class outside of any methods (that is, where the class variables are defined) AND it happens inside a list comprehension. Having the iteration inside list comprehension happening elsewhere doesn't seem to cause any issue. Let us look into it and see what's going on. Cheers.
