### ISSUE TITLE
LGTM.com - false positive This use of variable always evaluates to true.

### ISSUE THREAD

**Issue by andreasplesch** [Semmle/ql#2155]
**Description of the false positive**

The use of the variable does not always evaluate to true:

```js
 ( !vrDisplay || (vrDisplay && !vrDisplay.isPresenting) )
```

In the function, vrDisplay can be either undefined or an object.

If it is undefined, !vrDisplay is true and the whole expression always evaluates to true.
If it is an object, !vrDisplay is false and the whole expression evaluates to !vrDisplay.isPresenting which can be true or false.

So I am not sure where is alert is coming from. Perhaps LGTM assumes vrDisplay must be an object.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/x3dom/x3dom/snapshot/b492cfedcc33a57880ce87b95e90925fae9ec710/files/src/util/VRControllerManager.js?sort=name&dir=ASC&mode=heatmap#V240

**Comment by esben-semmle** [comment]
The variable use that the alert refers to is the second `vrDisplay` of that line. It is highlighted if you hover the alert message:

![image](https://user-images.githubusercontent.com/42067045/67181414-d4cbee00-f3dc-11e9-8463-e3eccd234add.png)

The alert specifically does not warn about the first use of `vrDisplay` or the entire condition expression.

So your condition expression can be simplified to:

```js
 ( !vrDisplay || !vrDisplay.isPresenting)
```

**Comment by andreasplesch** [comment]
Thanks. I could not rediscover the hover functionality ( though I had in the past ). 

The second use could evaluate to false if it would be evaluated. It just never is evaluated in that case. So the message is technically correct but requires an unexpected interpretation of 'This use'.

So there some usability aspects but I do not have concrete suggestions.

**Comment by esben-semmle** [comment]
I agree.
We track such LGTM UI issues internally, do you mind if I close this ticket?
