### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by ycrumeyrolle** [Semmle/ql#2156]
**Description of the false positive**
It is said that the `Disposable 'HttpClientHandler' is created here but is not disposed.`
The `HttpClientHandler` is provided to the `HttpClient` ctor, and this is the `HttpClient`, owner of the handler, that is disposed later and will dispose the handler.

**https://lgtm.com/projects/g/ycrumeyrolle/Jwt/snapshot/93f77e16c61737b955adb421a6ea1878cbc565dc/files/src/JsonWebToken/HttpDocumentRetriever.cs?sort=name&dir=ASC&mode=heatmap#xbfa19b9dc79eb770:1**

**Comment by calumgrant** [comment]
We have merged a fix for this issue, so changes to the results will appear the next time LGTM.com is updated.
