### ISSUE TITLE
LGTM.com - false positive (import.meta support)

### ISSUE THREAD

**Issue by brettz9** [Semmle/ql#2158]
**Description of the false positive**

`import.meta.url` is an emerging standard so it should not be an "unexpected token"; see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta and https://html.spec.whatwg.org/multipage/webappapis.html#hostgetimportmetaproperties .

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/brettz9/git-utilities/snapshot/64486327560879d1be1e9f57775008bf84b38ce6/files/tools/build-cli-svg.mjs?sort=name&dir=ASC&mode=heatmap#xe052b5532172a44e:1

Thanks!

**Comment by esben-semmle** [comment]
Thank you for the report. 
We have scheduled some work on `import.meta` already, it should be supported soon (@erik-krogh ).

**Comment by brettz9** [comment]
Sorry--any ETA on this? Have several projects that use this...

**Comment by erik-krogh** [comment]
We just merged support for `import.meta` in JavaScript files.  
It should be deployed to LGTM.com within in a few weeks.

**Comment by brettz9** [comment]
Super, thanks much! And thanks for all your work on this great project!

**Comment by brettz9** [comment]
I still haven't seem this land for at least my existing JS files, e.g., https://lgtm.com/projects/g/brettz9/intl-dom/snapshot/05bce31221432b6d9427d871e2f7feb05b3a1256/files/server.js?sort=name&dir=ASC&mode=heatmap

**Comment by max-schaefer** [comment]
Hi @brettz, I believe the change hasn't reached LGTM.com yet. ([This branch](https://github.com/Semmle/ql/tree/lgtm.com) points to the revision that is currently deployed.)

An upgrade is underway, however, so hopefully it should be a matter of a few days.

**Comment by erik-krogh** [comment]
The change reached LGTM.com a week or two ago, and the syntax error is no longer reported on your project.

I'm closing the issue.
