### ISSUE TITLE
LGTM.com - false positive (TypeScript 3.7 support)

### ISSUE THREAD

**Issue by kyranet** [Semmle/ql#2159]
**Description of the false positive**

`Error: Expression expected.` is raised when using the [optional chaining operator](https://github.com/tc39/proposal-optional-chaining), currently supported in `typescript@next`, `babel`, and Chrome 80 (haven't checked other browsers).

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/kyranet/Skyra/snapshot/569ccd85531c5b99fb275b2dec67c9a89ac82d83/files/database/5.2.0.ts

**Comment by asgerf** [comment]
Hi kyranet,

Thanks for the report. We plan to upgrade to TypeScript 3.7 shortly after a stable version is released.

**Comment by AlCalzone** [comment]
@asgerf  I'm not sure if there's an issue for all of the new syntax additions:
- optional chaining
- nullish coalescing
- `declare` inside classes

**Comment by asger-semmle** [comment]
> I'm not sure if there's an issue for all of the new syntax additions:

We don't have separate issues for each language feature. For now I think it's fine if you want to discuss other features from TypeScript 3.7. We intend to add support for all of them at once.

> `declare` inside classes

@AlCalzone I can't find any mention of this feature anywhere. Could you elaborate?

**Comment by AlCalzone** [comment]
It has been missing from both the beta and the RC release notes. I'll look it up for you

**Comment by AlCalzone** [comment]
https://github.com/microsoft/TypeScript/pull/33509

**Comment by AlCalzone** [comment]
Scroll down a bit in the PR description

**Comment by asger-semmle** [comment]
Thanks @AlCalzone! I didn't know about this feature so this was really helpful. I've added it to https://github.com/Semmle/ql/pull/2237.

**Comment by asger-semmle** [comment]
The update went live earlier this week, and the syntax errors seem to have gone away as expected.
