### ISSUE TITLE
LGTM.com - false positive - Wrong type of arguments to formatting function

### ISSUE THREAD

**Issue by kharwell** [Semmle/ql#2182]
**Description of the false positive**

The report states some arguments should be of type 'int'. However, according to the formatting these should be 'char *', which they are.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/asterisk/asterisk/snapshot/fc1984aff4ba37406bdb3c1d4410d6d735054599/files/res/res_pjsip/pjsip_scheduler.c?sort=name&dir=ASC&mode=heatmap#x2b8ee5131c5434ab:1

https://lgtm.com/projects/g/asterisk/asterisk/snapshot/fc1984aff4ba37406bdb3c1d4410d6d735054599/files/res/res_pjsip/pjsip_scheduler.c?sort=name&dir=ASC&mode=heatmap#x32077a9d8bca3ac7:1

https://lgtm.com/projects/g/asterisk/asterisk/snapshot/fc1984aff4ba37406bdb3c1d4410d6d735054599/files/res/res_pjsip/pjsip_scheduler.c?sort=name&dir=ASC&mode=heatmap#xd6952dc4b2cf0ef6:1

**Comment by jbj** [comment]
Thanks for the report.

@geoffw0, will you take a look? Perhaps our format-string parser is not quite up to the task of parsing a specifier like `%6$-*5$s`.

**Comment by geoffw0** [comment]
I believe we support each of the parts of that format string, but we don't have many tests of this overall complexity.  I'm thinking there could be an interaction we don't model correctly.

I'll find a gap in my schedule to fix this.

**Comment by geoffw0** [comment]
A fix for this has been merged (https://github.com/Semmle/ql/pull/2232) and should be effective on LGTM within about 2 weeks.
