### ISSUE TITLE
LGTM.com - false positive - JS - Path Traversal in Express sendFile

### ISSUE THREAD

**Issue by JLLeitschuh** [Semmle/ql#2197]
**Description of the false-positive**

The JavaScript library `express` contains a method on `ServerResponse` called `sendFile`:

- https://github.com/expressjs/express/blob/0a48e18056865364b2461b2ece7ccb2d1075d3c9/lib/response.js#L362-L442

This method relies upon another library called `send` called here:
 - https://github.com/expressjs/express/blob/0a48e18056865364b2461b2ece7ccb2d1075d3c9/lib/response.js#L430

The `send` library has it's own validation in place to prevent path traversal if the developer hasn't supplied their own `root` via the options parameter:

 - https://github.com/pillarjs/send/blob/de073ed3237ade9ff71c61673a34474b30e5d45b/index.js#L531-L562

This validation is using a regular expression to check for malicious path traversal in the supplied parameters:

- https://github.com/pillarjs/send/blob/de073ed3237ade9ff71c61673a34474b30e5d45b/index.js#L63

**When is this not a false-positive**

When user-supplied data is used to construct the full path, this is a security vulnerability.

However, if the application supplies the prefix for the path, and then user-supplied data is appended, this would generally not be considered a vulnerability as long as the user expects to expose everything under the base directory.

Example safe:
```javascript
res.sendFile("/my/safe/static/" + userSupplied);
```

**Example false-positive**

 - https://lgtm.com/projects/g/verdaccio/verdaccio/snapshot/ac2c53281e4f8cd14877457949521769eddb292a/files/src/api/web/index.ts?sort=name&dir=ASC&mode=heatmap#x1cf255e98ba45634:1

**Comment by esbena** [comment]
Wow. That is an impressive FP report! Well done.
We will improve the query to recognise such prefixed paths as safe soon.

**Comment by esbena** [comment]
@JLLeitschuh #2202 fixes the issue, it should be on LGTM.com in a few weeks.

**Comment by JLLeitschuh** [comment]
> Wow. That is an impressive FP report! Well done.

I did a deep dive on this one to try to figure out if that project linked was vulnerable.

Glad to see this FP resolved. I appreciate it!
