### ISSUE TITLE
LGTM.com - false positive Java: "Dereferenced variable may be null" on apache kafka

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [Semmle/ql#2238]
**Description of the false positive**

Both the assignment and the access of this variable are guarded by the same condition,
but somehow the correlated conditions code does not pick it up.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/apache/kafka/snapshot/df227dc5885602fcfe719b3827edd50697e99434/files/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java?sort=name&dir=ASC&mode=heatmap#x95b7db949153fa63:1

**Comment by kno10** [comment]
Similar false positive, simpler to see that its the same guard:

https://lgtm.com/projects/g/elki-project/elki/snapshot/7c238e44372782ba4b48b619493f62f356bb256f/files/elki-clustering/src/main/java/elki/clustering/em/EM.java#x106630dbd2f5371f:1
```
DoubleStatistic likestat = LOG.isStatistics() ? new DoubleStatistic(...) : null;
if(LOG.isStatistics()) {
  LOG.statistics(likestat.setDouble(loglikelihood));
}
```
I could avoid the LGTM warning by testing whether likestat is `null` instead, but this does not convey the _intention_ of checking the log level; and it is a best practise with java.util.logging to keep all logger calls guarded with such an if statement.

**Comment by HenryLoenwind** [comment]
Same one here https://lgtm.com/projects/g/SleepyTrousers/EnderIO/latest/files/enderio-machines/build/sources/main/java/crazypants/enderio/machines/machine/wired/ContainerWiredCharger.java?sort=name&dir=ASC&mode=heatmap#L77

But, tbh, the code analysis has no way of knowing if the result of the guard condition can/will change over time or not.

**Comment by kno10** [comment]
I have been considering that; and in a multi-threaded case it probably _could_ change, I guess, depending on the internals of java logging.  Still, I don't really like adding a null check there everywhere. In my case, there are many ways users can shoot themselves in the foot, beginning with using NaN values as parameters, but I will not do defensive copies because of performance either.

**Comment by kno10** [comment]
The object is lightweight and infrequently used enough to just instantiate it anyway (its set up this way in other places). There are some exceptions though, where for example the standard deviation of some value is collected. But probably a null guard then is appropriate.

**Comment by the-exodus** [comment]
As I was curious I dug into Java a bit to see what it offered. First of all, I must say I'm _so_ happy I'm not stuck with it :) Then I came up with this;

```java
Optional<DoubleStatistic> likestat = LOG.isStatistics() ? Optional.of(new DoubleStatistic("logLikelihood", loglikelihood)) : Optional.empty();
likestat.ifPresent(stat -> LOG.statistics(stat));
```

and even though this doesn't feel like the optimal context for it, you can be 100% sure you'll never try to invoke setDouble() on a null-ref. Optional<> was kind of cute, and I see how it can be useful.

Then I facepalmed a few times before just doing this
```java
if(LOG.isStatistics()) {
  var stat = new DoubleStatistic("logLikelihood", loglikelihood);
  LOG.statistics(stat);
}
```
and it just now occured to me that if `!LOG.isStatistics()`, anything logged at that output level will be filtered out anyway, so may as well just
```java
var stat = new DoubleStatistic("logLikelihood", loglikelihood);
LOG.statistics(stat);
```
I'd be very surprised if you got any warning about null references with that code...

**Comment by kno10** [comment]
By now you're completely off topic here.

**Comment by aschackmull** [comment]
Getting back on topic, this is about extending the Nullness analysis to recognize more types of correlated conditions.  Repeated `instanceof` test on the same SSA variable, as is the case in the FP in apache/kafka, shouldn't be too hard to add support for. @Cornelius-Riemenschneider maybe you'd like to make a PR with this change, as I know you've been digging around in the libraries?  The second FP with two instances of a boolean method that supposedly returns the same value every time is somewhat harder to handle as that involves writing an analysis to verify this property.  This is something that we're aware of, but unfortunately not something that we'll likely prioritise in the near future.

**Comment by Cornelius-Riemenschneider** [comment]
See the PR for the initially reported FP.
Another interesting FP is
https://lgtm.com/projects/g/apache/kafka/snapshot/0c566d99dba97128d001cb2d10b19cde075cef2d/files/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/RestServer.java#xa7733f26a546e3e:1
where the correlated conditions is of the form
```if (adminResourceConfig != resourceConfig)```
for the same SSA vars.
I also added a test+fix for that to the PR.
