### ISSUE TITLE
LGTM.com - false positive C# nunit (ex may be null with preceeding Assert.IsNotNull call)

### ISSUE THREAD

**Issue by tznind** [Semmle/ql#2250]
False positive is:

```
Variable ex may be null here because of this assignment.
```
The line highlighted is

```
  StringAssert.Contains([...],ex.Message);
```
But 

Line 653 includes the statement `Assert.IsNotNull` which makes the test fail if the variable is null.

```
Assert.IsNotNull(ex,[...]);
```
Link to the issue in lgtm is:

https://lgtm.com/projects/g/HicServices/FAnsiSql/snapshot/7800d62036807d9db4663d6929b2029e9b5084cc/files/Tests/FAnsiTests/Table/BulkInsertTest.cs?sort=name&dir=ASC&mode=heatmap#L653

This is unit test code though so I'm not sure if it's supposed to be skipped in the alert system altogether or if I am supposed to configure that on my repo.

**Comment by hvitved** [comment]
Hi

Thank you very much for reporting this, and sorry for not replying earlier. I agree that this looks like a false positive, and I well get back once I have investigated further.

**Comment by hvitved** [comment]
Here is the fix: https://github.com/Semmle/ql/pull/2340.
