### ISSUE TITLE
LGTM.com - false positive C# using without var (for IDisposable)

### ISSUE THREAD

**Issue by tznind** [Semmle/ql#2256]
I am getting `Disposable 'CancellationTokenSource' is created here but is not disposed.` when the object is within a using block.  The issue appears to be because the using statement is not in line with the declaration.

https://lgtm.com/projects/g/HicServices/FAnsiSql/snapshot/a78d70526551574114cb49e247b61294b6a18a0b/files/Tests/FAnsiTests/Table/BulkInsertTest.cs?sort=name&dir=ASC&mode=heatmap#xeb67661758642ffd:1

All the following should be valid ways of properly disposing an `IDisposable`.

```csharp
[Test]
public void Using()
{
	A myA;

	using (myA = new A())
	{
		Assert.IsFalse(myA.IsDisposed);
	}

	Assert.IsTrue(myA.IsDisposed);

	using (myA = new A())
	{
		Assert.IsFalse(myA.IsDisposed);
	}

	Assert.IsTrue(myA.IsDisposed);

	myA = new A();

	using (myA)
		Assert.IsFalse(myA.IsDisposed);

	Assert.IsTrue(myA.IsDisposed);
}

private class A : IDisposable
{
	public bool IsDisposed { get; set; }

	public void Dispose()
	{
		IsDisposed = true;
	}
}
```

**Comment by hvitved** [comment]
Hi

Thanks for another report. This definitely is a (rather embarrassing) false positive. I will investigate and get back with an update.

**Comment by hvitved** [comment]
Here is the fix: https://github.com/Semmle/ql/pull/2343. Thank you again for reporting this.
