### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by bjaraujo** [Semmle/ql#2298]
**Description of the false positive**

for (Integer i = 0; i < 4; ++i)
     a.row(i) << sPoints[i].x(), sPoints[i].y(), sPoints[i].z(), 1.0;

LGTM gets confused with operator overloading. Here I am using math library Eigen to assign a row to a given matrix.

https://lgtm.com/projects/g/bjaraujo/ENigMA/snapshot/da9570597b4efec3a581d6b37de8a0e64c919319/files/trunk/src/geometry/GeoSphere_Imp.hpp?sort=name&dir=ASC&mode=heatmap#x6c9591050cc7612b:1

**Comment by jbj** [comment]
Thank you for the report.

The comma is supposed to be an overloaded operator, but [our extractor sees it as a built-in operator](https://lgtm.com/query/5834235956851932974/). There are [two extraction errors](https://lgtm.com/query/1617618167128820365), but I'm not sure they are directly related to this problem.

We'll investigate further.
