### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by rlizzo** [Semmle/ql#2299]
**Description of the false positive**

This regex used an `r` `f-string` with a configuration variable name being replaced with the value to search for. It is not searching for the variable names characters in the replacement field. 

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/tensorwerk/hangar-py/snapshot/4a94812c263984239b03132c8f8f76cbaaf45a4f/files/src/hangar/backends/hdf5_00.py?sort=name&dir=ASC&mode=heatmap#xb4387382d0c2cc09:1

**Comment by RasmusWL** [comment]
Thanks for reporting this!

We made a fix for this in our internal repo, and it should be deployed to LGTM.com within the next few weeks :)
