### ISSUE TITLE
LGTM.com - false positive [Java, simple math]

### ISSUE THREAD

**Issue by HenryLoenwind** [Semmle/ql#2335]
It thinks `float height = 1 - ratio;` must always be null or negative, which is nonsense even when looking at the source for `ratio` (it returns a float `[0,1]` which then is limited to `(0,1]`, so `height` is `[0,1)`).

https://lgtm.com/projects/g/SleepyTrousers/EnderIO/latest/files/enderio-base/build/sources/main/java/crazypants/enderio/base/render/util/TankRenderHelper.java#x66434a78246bebea:1

**Comment by aschackmull** [comment]
Thank you for your report.  I've submitted a PR to fix this issue.
