### ISSUE TITLE
LGTM.com - false positive [Java, non-overflow]

### ISSUE THREAD

**Issue by HenryLoenwind** [Semmle/ql#2336]
`sendPrio` can never go above 200 (lines 180 and 184 are the only assignments and they are logically linked), so `sendPrio * 2` cannot overflow `int`.

https://lgtm.com/projects/g/SleepyTrousers/EnderIO/latest/files/enderio-machines/build/sources/main/java/crazypants/enderio/machines/machine/tank/TileTank.java#L183

(Aside from having `(Integer.MAX_VALUE - 200)/2` additional threads doing the same, I guess. However, IMO, assuming objects are thread-locked by default makes sense as most environments are either set up that way or require much more extensive thread-safety checks.)

**Comment by aschackmull** [comment]
This is indeed a short-coming in our range analysis, but as you've noticed, changing `2` to `2L` is an easy fix.  Updating the range analysis to account for this case is unfortunately not an easy task, so we're likely not going to be able to prioritise this in the near future.
