### ISSUE TITLE
LGTM.com - false positive C++: "Comparison result is always the same" + thread_local

### ISSUE THREAD

**Issue by PearCoding** [Semmle/ql#2352]
Variable declared as `thread_local` is not detected as changeable and triggers a "Comparison result is always the same", which is wrong due to line 75 in the same file and function.

https://lgtm.com/projects/g/PearCoding/PearRay/snapshot/e2f023be537096d15526e7a46cafd689dbd56b4a/files/src/library/Profiler.cpp?sort=name&dir=ASC&mode=heatmap#xc47b2ee0501fa466:1

**Comment by jbj** [comment]
Thank you for the report. It'll be trivial to fix in isolation, but we're just debating whether to make broader library changes to ensure correct handling of `thread_local` in all the other queries too. I'll follow up when we have a PR open.
