### ISSUE TITLE
LGTM seems to be ignoring suppression comment

### ISSUE THREAD

**Issue by michaelrsweet** [Semmle/ql#2385]
I have added a comment to the end of line 986 for this alert:

https://lgtm.com/projects/g/apple/cups/snapshot/8ed6c5712325c95d0a94769e305692504389303d/files/cgi-bin/var.c?sort=name&dir=ASC&mode=heatmap#xca8c369060201c3:1

However I still see the alert (see attached screenshot).
<img width="1278" alt="Screen Shot 2019-11-19 at 8 28 40 AM" src="https://user-images.githubusercontent.com/488103/69150596-0355eb00-0aa7-11ea-9287-c1b7e7511ab7.png">

**Comment by jbj** [comment]
I'm afraid we only allow `//`-style comments for alert suppression.
