### ISSUE TITLE
LGTM.com - false positive in js/react/unused-or-undefined-state-property with getDerivedStateFromError

### ISSUE THREAD

**Issue by muescha** [Semmle/ql#2389]
**Description of the false positive**

Rule: [js/react/unused-or-undefined-state-property](https://lgtm.com/rules/1506221406550/)

```javascript
Component state property 'error' is read, but it is never written.
```

but `error` is written in [Line 30](https://lgtm.com/projects/g/gatsbyjs/gatsby/snapshot/f057bb31bbd87d30a890eb827a384e9917e2cb38/files/packages/gatsby-cli/src/reporter/loggers/ink/cli.js?sort=name&dir=ASC&mode=heatmap#L30)

```javascript
static getDerivedStateFromError(error) {
	return { hasError: true, error }
}
```

https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror

> `static getDerivedStateFromError(error)`
>
> This lifecycle is invoked after an error has been thrown by a descendant component. It receives the error that was thrown as a parameter and should return a value to update state.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/gatsbyjs/gatsby/snapshot/f057bb31bbd87d30a890eb827a384e9917e2cb38/files/packages/gatsby-cli/src/reporter/loggers/ink/cli.js?sort=name&dir=ASC&mode=heatmap#V15

**similar issues**

#670

**Comment by esbena** [comment]
Thank you for the report.
A fix is inbound from #2394, it should be live in a few weeks time.
