### ISSUE TITLE
JS bogus 'use of returnless function' with Function.prototype.call

### ISSUE THREAD

**Issue by minj** [Semmle/ql#2398]
See https://lgtm.com/projects/g/minj/foxtrick/snapshot/86707c213526a70e3a74b760ea06338715a23355/files/content/util/dom.js?sort=name&dir=ASC&mode=heatmap#x571bf5c1337646c:1

**Comment by erik-krogh** [comment]
Yes, that is a false positive. Thanks for the report. 

We have actually fixed it already (https://github.com/Semmle/ql/pull/2270), we are just waiting for the fix to deploy on LGTM.   
That should happen within a few weeks. 

I just ran a test locally, and the fix does remove the false positives in your `foxtrick` project.

**Comment by minj** [comment]
Thanks for the quick response. Looking forward to it.

**Comment by erik-krogh** [comment]
The fix has been deployed to LGTM, so the false positives you reported no longer appear. 

I'm closing the issue.
