### ISSUE TITLE
LGTM.com - false positive for type annotation usage

### ISSUE THREAD

**Issue by maxfischer2781** [Semmle/ql#2407]
**Description of the false positive**

LGTM reports an unused import if a) a type is imported *without* ``if TYPE_CHECKING`` guard and b) the type is used only in a quoted type annotation.

```python3
from typing import Iterable, Any, TYPE_CHECKING, Union
# LGTM reports "Import of 'Union' is not used."

...

class PrimitiveExpression(Expression):
    ...
    def __htc_eq__(
        self, b: "PrimitiveExpression"
    ) -> "Union[PrimitiveExpression, Undefined, Error]":
        # LGTM misses use of Union in quoted annotation
        return NotImplemented
```
While in this case, ``Union`` itself would not need quoting (not a cyclic use) its members need quoting. [PEP 484 allows selective quoting](https://www.python.org/dev/peps/pep-0484/#forward-references) but does not enforce it, and common Python linters/checkers (``flake8`` in our case) require the entire expression to be quoted.

This report is related to #2014 and its fix #2042, which appears to cover b) *iff not* a).

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/MaineKuehn/classad/snapshot/efb412d5963def8986a00aee1e6adf52d23f1076/files/classad/_base_expression.py?sort=name&dir=ASC&mode=heatmap#xfd6c2c36902cc3f0:1

**Comment by tausbn** [comment]
Ah, this looks to be a simple oversight on our part. the #2042 covers the case where the forward reference appears inside a parameter annotation, but does not cover the case where it appears inside the return type itself.

(Thank you, by the way, for these excellent reports! They have been very helpful. :slightly_smiling_face:)
