### ISSUE TITLE
LGTM.com - false positive - lgtm [js/unused-local-variable] comment ignored

### ISSUE THREAD

**Issue by greggman** [Semmle/ql#2416]
**Description of the false positive**

I added `lgtm [js/unused-local-variable]` as a comment but lgtm ignored the comment

Here's the code

```
// make sure we don't see a global gl
const gl = undefined;  /* eslint-disable-line */ /* lgtm [js/unused-local-variable] */
```

https://lgtm.com/projects/g/greggman/twgl.js/snapshot/96d12418bbf83072d9c55e7c6ca5156c17d40a4f/files/src/programs.js?sort=name&dir=ASC&mode=heatmap#xde980cc0015b22b6:1

**Comment by max-schaefer** [comment]
Thank you for your report. Suppression comments currently have to be line comments starting with `//` as shown in the documentation. It is probably worth stating more explicitly that block comments don't work, I'll look into updating the documentation.

**Comment by greggman** [comment]
That sounds pretty bad. Lots of different services will all want to be the last comment 😕

**Comment by max-schaefer** [comment]
Thank you for your feedback; we'll consider whether we can relax this restriction.

Meanwhile, an update to the documentation to make this clearer is on its way to being deployed in the next few weeks.

**Comment by greggman** [comment]
I  see. Well I guess I'll just use .lgtm.yml to disable this so the code doesn't get mis-judged
