### ISSUE TITLE
LGTM.com - false positive - lgtm comments ignored

### ISSUE THREAD

**Issue by greggman** [Semmle/ql#2423]
**Description of the false positive**

Alert shows

<img width="702" alt="Screen Shot 2019-11-23 at 19 06 49" src="https://user-images.githubusercontent.com/234804/69477016-7b643e00-0e24-11ea-8d98-4e5781d68fd0.png">

https://lgtm.com/projects/g/greggman/servez-lib/snapshot/4b63db6291052b09289b37fb60c420cfd85a976b/files/lib/compression.js?sort=name&dir=ASC&mode=heatmap#xf8743ff32ed3cb46:1

I'm told I need to use `//` comments instead of `/* */` comments.

I fix it

lgtm says it's not fixed

https://lgtm.com/projects/g/greggman/servez-lib/rev/pr-c682e535d562c8c5eaf23f190cc2d34270f33cde

<img width="706" alt="Screen Shot 2019-11-23 at 18 58 42" src="https://user-images.githubusercontent.com/234804/69476933-620ec200-0e23-11ea-85a9-efbc84ff3e40.png">

**URL to the alert on the project page on LGTM.com**

**Comment by max-schaefer** [comment]
While I agree that this is surprising behaviour, it is documented [here](https://help.semmle.com/lgtm-enterprise/user/help/alert-suppression.html): "alert suppression changes made in a pull request are only applied when that pull request is merged".
