### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by nekokatt** [Semmle/ql#2426]
**Description of the false positive**

Python 3.7 introduced the `annotations` future import which allows post-loading annotation evaluation. 

This allows you to have circular references between two modules and it not prevent the file importing.

Suppose the following example:

`module1.py`
```py
from __future__ import annotations

import dataclasses
import typing

import module2

@dataclasses.dataclass()
class Foo:
    bars: typing.List[module2.Bar]
```
`module2.py`
```py
from __future__ import annotations

import dataclasses
import typing

import module1

@dataclasses.dataclass()
class Bar:
    def is_in_foo(self, foo: module1.Foo):
        return self in foo.bars
```
With the `__future__` import, this is perfectly valid code that runs, yet LGTM is throwing many errors in the face of this. While I could potentially use `"string"` type hints, that hurts readability, partially because Sphinx will then contain this as a `ForwardRef[type]` which is confusing to the reader as it has no impact on how they use the code I provide them in my library.

LGTM page:
https://lgtm.com/projects/gl/nekokatt/hikari/snapshot/fb3f0e4fe8b93a87ebc2ecd6bb47ed1c6a0bf5d8/files/hikari/orm/state_registry.py?sort=name&dir=ASC&mode=heatmap#xda2665496cb4357d:1

Proof that this is incorrect: 
https://gitlab.com/nekokatt/hikari/-/jobs/359628333#L1537

```
 ======================= 961 passed, 24 skipped in 23.59s =======================
```

----

Potential workarounds that could be implemented until this bug is fixed:

1. Allow suppression of specific checks per file (`# suppressall <code>` or similar at the top of the file after the shebang and magic comment?). Ideally we should have the ability to do this anyway rather than having many suppression comments on multiple lines, especially as this makes code incredibly messy if you do it more than a few times. Remember many of these checks can be considered subjective depending on the use case.

2. Allow suppression of specific checks per repository (`.lgtmignore` or similar in repository base)

3. Allow hiding of checks per project in settings.

**Comment by nekokatt** [comment]
Sidenote, I have added an exclusion to [lgtm.yml](https://gitlab.com/nekokatt/hikari/blob/staging/lgtm.yml#L13) as suggested by the documentation to suppress this warning, which has worked to hide it, however, ideally this shouldn't need to be suppressed as there are other cases where this check would be overly useful.

**Comment by tausbn** [comment]
Thank you for your detailed report! The fix referenced above should go live in a few weeks.

In general, I don't think it's likely we will add the suppression options you suggest. The danger with such blanket suppressions is -- as you point out -- that they may hide useful alerts. The right course of action in this case is exactly what you did: report it and wait for a fix. :slightly_smiling_face:
