### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by jSylvestre** [Semmle/ql#2437]
**Description of the false positive**
Useless assignment to local variable

This value is checked and used on this line:
https://lgtm.com/projects/g/ucdavis/Peaks/snapshot/8fe0a59150ae54992c5c177eb7090e649444d68e/files/Keas.Mvc/Helpers/DbInitializer.cs?sort=name&dir=ASC&mode=heatmap#L59

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/ucdavis/Peaks/snapshot/8fe0a59150ae54992c5c177eb7090e649444d68e/files/Keas.Mvc/Helpers/DbInitializer.cs?sort=name&dir=ASC&mode=heatmap#xaefa2cbda47943a0:1

**Comment by hvitved** [comment]
Hi.

I just checked the results, and they look genuine to me. For example, the local variable `keyMaster` on [line 25](https://lgtm.com/projects/g/ucdavis/Peaks/snapshot/8fe0a59150ae54992c5c177eb7090e649444d68e/files/Keas.Mvc/Helpers/DbInitializer.cs?sort=name&dir=ASC&mode=heatmap#L25) is not read anywhere, hence the assignment is useless. Of course, the expression that computes the value (`CreateOrFindRole(new Role { Name = "KeyMaster" })`) may still be needed for its side-effects, but the result is not used, so there is no need to assign it to a local variable.

**Comment by jSylvestre** [comment]
@hvitved Oops, you are correct.  My mistake.
Thanks.
