### ISSUE TITLE
LGTM.com - false positive (Java constants)

### ISSUE THREAD

**Issue by HenryLoenwind** [Semmle/ql#2440]
The check for "Expression always evaluates to the same value." needs to take into account that constants (static final) are most likely intentionally are set to the same value every time. With those it also is good practice to write down even meaningless calculations so any person who's to read the code in the future can understand where your magic number came from.

The same probably is true for calculations from literals and constants in runtime code. The result is always the same, it's just written that way to be readable for humans.

https://lgtm.com/projects/g/SleepyTrousers/EnderIO/snapshot/e76a8b98d9f06521ed4b6712e66e5c82c7b6ce01/files/enderio-machines/build/sources/main/java/crazypants/enderio/machines/machine/killera/BlockKillerJoe.java?sort=name&dir=ASC&mode=heatmap#x47f3504b2ec46830:1

**Comment by aschackmull** [comment]
I agree that patterns of the form `0 * x` where the zero is a literal `0` and not the result of computation are usually intended.  I'll make a PR to adjust the query.
