### ISSUE TITLE
ERROR: Could not resolve type Call!

### ISSUE THREAD

**Issue by imanoracle** [Semmle/ql#2446]
Hello,
I am running the following query (it is okay on LGTM query console):
```
/**
 * @name test
 * @description test
 * @kind problem
 * @problem.severity recommendation
 * @precision low
 * @id java/empty-finalizer
 * @tags reliability
 *       readability
 *       external/cwe/cwe-568
 */
import java
import semmle.code.java.dataflow.FlowSources
import DataFlow::PathGraph

class FlowConfig extends TaintTracking::Configuration {
 	 FlowConfig() { this = "FlowConfig"} 
  	 override predicate isSource(DataFlow::Node source){
         source instanceof RemoteFlowSource
  	 }
  
  	 override predicate isSink(DataFlow::Node sink){
        exists(Call c | c.getCallee().hasName("fromXML") and c.getAnArgument() = sink.asExpr())
     }
}

from FlowConfig cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select source , source, sink, "Mesage"
```
Command : `codeql database analyze testRule "/home/XXX/codeql/ql/java/ql/src/Violations of Best Practice/Dead Code/EmptyFinalize1.ql" --format=csv --output=/tmp/test.csv `
But I am getting the following error:
`ERROR: Could not resolve type Call (/home/isharafa/codeql/ql/java/ql/src/Violations of Best Practice/Dead Code/EmptyFinalize1.ql:14,6-10)`

Could you please help me to find out where is the problem?

**Comment by p0** [comment]
Hi @imanoracle -- it looks to me like the command you're running should work, but something is odd: the error message reports `Call` undefined on line 14, which is not where it is for the QL code you provided. Could it be that you're processing a different file?

To debug this further, could you share the output of `codeql query compile -vv "/home/isharafa/codeql/ql/java/ql/src/Violations of Best Practice/Dead Code/EmptyFinalize1.ql"`?

**Comment by imanoracle** [comment]
Thank you @p0, you are right the filename was EmptyFinalize2.ql. 
Sorry.

Thanks.
