### ISSUE TITLE
LGTM.com - false positive Python multiline text

### ISSUE THREAD

**Issue by scivision** [Semmle/ql#2453]
SyntaxError when multiline text is actually OK syntax.

https://lgtm.com/projects/g/scivision/PyLivestream/snapshot/9d210e34128db51b92d1887cd660a8598dba221c/files/pylivestream/ffmpeg.py?sort=name&dir=ASC&mode=heatmap#x5ddb34cb63b681ff:1

**Comment by tausbn** [comment]
We have created a fix for this, which should go live in a few weeks time. I will close this issue once I have verified that the syntax error has disappeared.

**Comment by scivision** [comment]
Thank you. Is the general timeline for getting fixes going live about a few weeks? because there is another LGTM fix I need that was merged into master about 3 days ago and I haven't seen it go live yet. Just curious.

**Comment by tausbn** [comment]
Yeah, upgrading LGTM.com is a somewhat time-consuming process, as it involves building new snapshots for all of the 135.000+ repos we track there. For this reason it's only done roughly once per fortnight.
