### ISSUE TITLE
C# tests that are sensitive to default toString() methods

### ISSUE THREAD

**Issue by hmakholm** [Semmle/ql#2518]
With the CodeQL CLI, the handling of `toString()` methods in QL changes. The default compilation mode in Odasa was that entity classes that don't declare a `toString()` inherit the default implicit `none()` behavior. In contrast, the new CodeQL CLI compiles with `--default-to-string` by default, which corresponds to a default behavior that could be expressed as
```
String toString() { result = "" }
```

These differences also apply between `odasa qltest` and (the yet-to-be-released) `codeql test run`. There are a few existing tests where this difference matters -- namely where a missing `toString()` definition in the library and/or test code previously made some row _disappear from the output_ due to not having any string representation. Thus the existing `.expected` file will not contain these rows, but `codeql test run` _will_ produce them, making the test fail.

It has been decided that this ought to be fixed by making sure that tests always declare all relevant `toString()` methods, such that their output is independent of the compilation mode.

For C#, the tests affected are:

- [x] `ql/csharp/ql/test/library-tests/linq/Linq1.ql`
- [x] `ql/csharp/ql/test/library-tests/controlflow/guards/AbstractValue.ql`
- [x] `ql/csharp/ql/test/library-tests/dataflow/global/TaintTrackingEdges.ql`
- [x] `ql/csharp/ql/test/library-tests/dataflow/global/DataFlowEdges.ql`

Please fix these -- ideally by making sure the relevant entity classes have `toString()` methods, but in a pinch just by injecting some `and a.toString() != ""` conditions in the `select` clauses.

To test that your fix works:
 1. check out branch `pr/test-extract` of `git.semmle.com/henning/code`
     - if this branch doesn't exist, it might be that #35764 has been merged, in which case you can just use `Semmle/code/master`.
 2. build `target/intree/codeql`.
 3. try running your test both with `codeql test run path/to/test.ql` and with `codeql test run --no-default-to-string path/to/test.ql`.

(Once all the tests have been updated, we will modify the behavior of `odasa qltest` appropriately, so a new divergence between the tools won't arise).

**Comment by hvitved** [comment]
When I run one of the tests it fails with a timeout (presumably because query optimization is disabled):
```
code/ql/csharp  codeql test run ql/test/library-tests/controlflow/guards/AbstractValue.ql  
Executing 1 tests in 1 directories.
Extracting test database in /Users/hvitved/Work/code/ql/csharp/ql/test/library-tests/controlflow/guards.
Compiling queries in /Users/hvitved/Work/code/ql/csharp/ql/test/library-tests/controlflow/guards.
Executing tests in /Users/hvitved/Work/code/ql/csharp/ql/test/library-tests/controlflow/guards.
[1/1 comp 530ms eval 5m0s] FAILED(EXECUTION) /Users/hvitved/Work/code/ql/csharp/ql/test/library-tests/controlflow/guards/AbstractValue.ql
0 tests passed; 1 tests failed:
  FAILED: /Users/hvitved/Work/code/ql/csharp/ql/test/library-tests/controlflow/guards/AbstractValue.ql
code/ql/csharp  
```
What did you do to avoid this?

**Comment by hmakholm** [comment]
`--no-fast-compilation` to re-enable optimization. (I'm strongly considering to make this the default again).

And I see the actual explanation of what failed seems to be lost for text output -- I'll fix that.
