### ISSUE TITLE
Non-alert-suppression despite code comment

### ISSUE THREAD

**Issue by brettz9** [Semmle/ql#253]
Despite my having an alert-suppression comment (at https://lgtm.com/projects/g/brettz9/C2D2/snapshot/4f8a73b02cc0ff4bc44c09a3ee6de709195d5712/files/explorercanvas/silverlight/excanvas.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#V158 ) and despite your site having my latest code, I find the alert is still showing. I guess this is because it is a multiline comment, but as your docs refer to the semi-colon, I was expecting it needed to be at the end of the statement...

*Update*: In the meantime, I just added a commit to add the alert suppression comment on the same line as the `document.write`, so will see what happens...

**Comment by xiemaisi** [comment]
Thank you for your report. For multi-line alerts, the suppression comment needs to go on the first line (so your follow-up commit worked). This isn't properly documented at the moment, apologies; we'll fix that.

**Comment by xiemaisi** [comment]
The documentation has been updated to clarify this.
