### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by Sprax2013** [Semmle/ql#2539]
**Description of the false positive**
LGTM tells me that I don't have any CSRF protection and points to an express-route that doesn't access that session-cookie (`req.session`). I'll move the middleware a bit down so that route can be contacted and skip the middleware. I think that will stop LGTM from detecting but it still is a false-positive.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/Mc-Auth-com/Mc-Auth-Web/snapshot/8bd0dbe24320c793f24992d001986a6ddc11b7c5/files/server.js?sort=name&dir=ASC&mode=heatmap#x548881a38f2438d4:1

**Comment by max-schaefer** [comment]
Thank you for your report! Unfortunately this query is a little prone to false positives, we'll look into sprucing it up a bit to avoid falsely flagging this code.

**Comment by asgerf** [comment]
Closing as the reported false positive has been fixed.

@Sprax2013 it seems to me the remaining alerts are true positives, but please let us know if you think that's not the case.
