### ISSUE TITLE
Badge examples are invalid and unusable

### ISSUE THREAD

**Issue by nekokatt** [Semmle/ql#2543]
The repository badges are not valid with shields.io and return a 404 not found response.

![Screenshot_20191217-121934](https://user-images.githubusercontent.com/52883826/70995174-d4439100-20c7-11ea-823d-8e6fec98bcef.jpg)

The URLs need to be updated to:

- lgtm/alerts/:host/:user/:repo
- lgtm/grade/:language/:host/:user/:repo

Example project used: https://lgtm.com/projects/gl/nekokatt/hikari/ci/

**Comment by chrisgavin** [comment]
Hi, we've updated our link generation for GitLab projects so these badges should now have correct image URLs again. Thanks for reporting this issue.
