### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by rsmarples** [Semmle/ql#2544]
Comparison of narrow type with wide type in loop condition

This is triggered by using the RTA_OK macro from rtnetlink(7) on Linux.
Basically the RTA_OK macro checks that the size of struct rtattr and it's length property are inside the length parameter passed to the macro.
Because the RTA macros take an unsigned int as a parameter and the length attribute is an unsigned short this warning will always trigger.
RTA_OK is designed to be used in a loop with RTA_NEXT.

This is impossible to fix without using a custom macro.

I also feel that it's bogus because the payload length decrements rather than increaments in the LGTM example of "wrong code" for this issue.

I think the correct solution is not to analyse the comparison but to analyze the increament of the next item - ie a smaller type is modified by a larger type.

https://lgtm.com/projects/g/rsmarples/dhcpcd/snapshot/f352a583b2e7b96546500652dba67f119db089d6/files/src/if-linux.c?sort=name&dir=ASC&mode=heatmap#x32af5f8a622bce61:1

**Comment by rsmarples** [comment]
Re-writing it from `while (RTA_OK(rta, len)) { ... rta = RTA_NEXT(rta, len); }` to `for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {` solves the issue.

Maybe this could be included in the example to help others out.

**Comment by jbj** [comment]
Thank you for the report. I think it's similar to what was reported in #2425, which we fixed in #2427. The fix took longer than usual to reach lgtm.com, but it was deployed yesterday. Let me know if the issue still persists.

**Comment by rsmarples** [comment]
It looks similar enough, but the code has been reworked to avoid the issue.
But as it deployed at the same time maybe my code change didn't avoid the issue.

Either way I'm happy and the resulting binary is surprisingly smaller!
