### ISSUE TITLE
LGTM.com - false positive - dereferenced-value-may-be-null

### ISSUE THREAD

**Issue by wumpz** [Semmle/ql#2553]
**Description of the false positive**

> `orderBy.toStringOrderByElements(b);`
> Variable orderBy may be null here as suggested by this null guard.

But **orderBy** is initialized as a final instance variable using:
`private final OrderByClause orderBy = new OrderByClause();`

Therefore it definitely has a value.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/JSQLParser/JSqlParser/snapshot/3804d2aedced2cf3b77931c83466402820cc0283/files/src/main/java/net/sf/jsqlparser/expression/AnalyticExpression.java?sort=name&dir=ASC&mode=heatmap#xda2d6e92c3feee7e:1

**Comment by aschackmull** [comment]
You are completely right that `orderBy` definitely is non-null, so this is indeed a FP.  But the subsequent null check that the alert points to is also clearly superfluous (and a false negative for the superfluous null check query).  I'll take a look at fixing this.

**Comment by wumpz** [comment]
You are so right. Now we both have something to fix ;).
