### ISSUE TITLE
LGTM.com - false positive - Java - Array index out of bounds - In loop when length check breaks out of loop

### ISSUE THREAD

**Issue by PascalSchumacher** [Semmle/ql#2560]
**Description of the false positive**

```java
String[] paths = path.split("/");
String[] consumerPaths = consumerPath.split("/");
for (int i = 0; i < consumerPaths.length; i++) {
    if (paths.length < i) {
        break;
    }
    String p1 = consumerPaths[i];
    if (p1.startsWith("{") && p1.endsWith("}")) {
        String key = p1.substring(1, p1.length() - 1);
        String value = paths[i]; // This array access might be out of bounds, as the index might be equal to the array length.
        if (value != null) {
            NettyHttpHelper.appendHeader(headers, key, value);
        }
    }
}
```

`paths[i]` can not be out of bounds, because of the `paths.length < i` check at the start of the loop.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/camel/snapshot/df896d95705fc3ef5eb6635b5f00e707cbb9812d/files/components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/RestNettyHttpBinding.java?sort=name&dir=ASC&mode=heatmap#xf8eebb9c26066de2:1

**Comment by aschackmull** [comment]
This looks like a true positive to me. If `paths.length == i` then you won't break out of the loop and you'll get an out-of-bounds access to the array.  Perhaps the check ought to have been `paths.length <= i` instead?

**Comment by PascalSchumacher** [comment]
You are correct. This issue is invalid. Sorry!
