### ISSUE TITLE
LGTM.com - false positive - Java - Dereferenced variable may be null - With early return Xor

### ISSUE THREAD

**Issue by PascalSchumacher** [Semmle/ql#2565]
**Description of the false positive**

In this code:

```java
public static boolean contentEquals(final File file1, final File file2) throws IOException {
    if (file1 == null && file2 == null) {
        return true;
    }
    if (file1 == null ^ file2 == null) {
        return false;
    }
    final boolean file1Exists = file1.exists();  // Variable may be null here
    // further code omitted
}
```

The previous early return statements guard against `file1` beeing `null`.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/commons-io/snapshot/15024f6da9fe7afdfd24d77d8394fbb602888e9e/files/src/main/java/org/apache/commons/io/FileUtils.java#x390d5fe3f9708330:1

I am not sure if this is worth reporting, as code like this is not common. Feel free to close if is not relevant.

**Comment by aschackmull** [comment]
You are correct that this is a FP.  It is a known issue that guards involving xor aren't handled very well; this is because such guards generally need to be combined with other guards to yield useful information, so they're tricky to deal with, and they aren't that common as you also note.
