### ISSUE TITLE
LGTM.com - false positive - Java - Boxed variable is never null - Boolean

### ISSUE THREAD

**Issue by PascalSchumacher** [Semmle/ql#2566]
**Description of the false positive**

This code:

```java
Boolean includeHostName = camelContext != null && camelContext.getManagementStrategy().getManagementAgent().getIncludeHostName();
```

generates this warning:

`The variable 'includeHostName' is only assigned values of primitive type and is never 'null', but it is declared with the boxed type 'Boolean'.`

but `ManagementAgent#getIncludeHostName` returns an `Boolean` object:

```java 
public interface ManagementAgent extends Service {
   Boolean getIncludeHostName();
}
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/camel/snapshot/ecdf9717151549f681bb3afe6c8ef41968b7ae2a/files/core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectNameStrategy.java?sort=name&dir=ASC&mode=heatmap#x612f7a4ad7c9d545:1

**Comment by aschackmull** [comment]
This is actually a true positive.  Since the `includeHostName` is calculated using `&&` it cannot be `null` (so if `getIncludeHostName()` returns `null` you'll get an exception).

**Comment by PascalSchumacher** [comment]
You are correct. This issue is invalid. Sorry!
