### ISSUE TITLE
General issue - Have a question about DataFlow

### ISSUE THREAD

**Issue by qazbnm456** [Semmle/ql#2567]
Hi there, thanks for this great work.

I have a question regarding DataFlow for these three cases below:

This is the `CodeQL` query to find a `Path`:
```
/** @kind path-problem */

import javascript
import DataFlow
import DataFlow::PathGraph

class ExampleTaint extends TaintTracking::Configuration {
  ExampleTaint() { this = "Example" }

  override predicate isSource(Node node) {
    exists(DeclStmt ds, VariableDeclarator d |
      d = ds.getADecl() and
      d.getBindingPattern().getAVariable().getName() = "source" and
      node = exprNode(d.getInit())
    )
  }

  override predicate isSink(Node node) {
    exists(FunctionNode f |
      f.getName() = "sink" and
      node = f.getParameter(0)
    )
  }
}

from ExampleTaint cfg, PathNode source, PathNode sink
where cfg.hasFlowPath(source, sink)
select sink, source, sink, "Source is at $@.", source, "here"
```

To the first example, a `Path` is found:
```
// index.js
const sink = require('./lib.js');
const source = 'source'; // Step. 1

sink(source);  // Step. 2
```
```
// lib.js
module.exports = function sink(val) { // Step. 3
  console.log(val);
};
```

To the second example, no `Path` is found:
```
// index.js
const fn = require('./lib.js');
const sink = fn();
const source = 'source';

sink(source); 
```
```
// lib.js
module.exports = function fn() { // a function returning another function
  function sink(val) {
    console.log(val);
  }

  return sink;
};
```

I'm not sure if `CodeQL` could find a `Path` if intermediate routes containing a function returning another function. Or, should I miss something?

Thank you!  😊

**Comment by max-schaefer** [comment]
Hi @qazbnm456,

Many thanks for your question. You are exactly right: while our JavaScript analysis can handle some uses of higher-order functions (mostly for reasoning about callbacks), the case of one function returning another is only partially supported. We'll look into whether it would be feasible to add support for the case you describe.
