### ISSUE TITLE
LGTM.com - false positive C# switch pattern matching with 'when' filters

### ISSUE THREAD

**Issue by Szune** [Semmle/ql#2571]
**Description:**
The false positive occurs when pattern matching in a switch statement on a type where the 'when' filters make up the actual check, as can be seen in these examples:
```csharp
switch(type)
{
    case var _ when type == typeof(string):
        break;
    case var _ when type == typeof(int):
        break;
}
```

**Reasoning:**
While it is true that the first part ```case var _``` always matches, the second part does not.
I guess what's required is an extra check for a 'when' filter if the type pattern always matches?

**Link:**
https://lgtm.com/projects/g/Szune/eilang/snapshot/f88cadcf580327fa80fef86489e137b5ab036841/files/eilang/Extensions/ValueExtensions.cs?sort=name&dir=ASC&mode=heatmap#xc2f1306e2149b148:1

I'm very happy with LGTM, by the way, it's an incredibly useful tool!

**Comment by hvitved** [comment]
Thank you for reporting this, and glad to hear that you like LGTM :-)

One way to avoid these alerts is to rewrite your code from
```csharp
            var type = obj.GetType();
            switch (type)
            {
                case var _ when type == typeof(string):
                    return factory.String((string) obj);
                case var _ when type == typeof(int):
                    return factory.Integer((int) obj);
                case var _ when type == typeof(long):
                    return factory.Long((long) obj);
                case var _ when type == typeof(double):
                    return factory.Double((double) obj);
                case var _ when type == typeof(bool):
                    return factory.Bool((bool) obj);
                case var _ when type == typeof(IntPtr):
                    return factory.IntPtr((IntPtr) obj);
                case var _ when !type.IsAbstract && !type.IsPrimitive: // probably going to need more guards here
                    return ConvertToEilangInstance(type, obj, factory);
                default:
                    throw new NotImplementedException();
            }
```
to
```csharp
            switch (obj)
            {
                case string s:
                    return factory.String(s);
                case int i:
                    return factory.Integer(i);
                case long l:
                    return factory.Long(l);
                case double d:
                    return factory.Double(d);
                case bool b:
                    return factory.Bool(b);
                case IntPtr ip:
                    return factory.IntPtr(ip);
                default:
                    var type = obj.GetType();
                    if (!type.IsAbstract && !type.IsPrimitive) // probably going to need more guards here
                        return ConvertToEilangInstance(type, obj, factory);
                    throw new NotImplementedException();
            }
```
Such a rewrite should also be more performant, as you avoid double type checks in each case.

**Comment by Szune** [comment]
> Thank you for reporting this, and glad to hear that you like LGTM :-)
> 
> One way to avoid these alerts is to rewrite your code from
> 
> ```cs
>             var type = obj.GetType();
>             switch (type)
>             {
>                 case var _ when type == typeof(string):
>                     return factory.String((string) obj);
>                 case var _ when type == typeof(int):
>                     return factory.Integer((int) obj);
>                 case var _ when type == typeof(long):
>                     return factory.Long((long) obj);
>                 case var _ when type == typeof(double):
>                     return factory.Double((double) obj);
>                 case var _ when type == typeof(bool):
>                     return factory.Bool((bool) obj);
>                 case var _ when type == typeof(IntPtr):
>                     return factory.IntPtr((IntPtr) obj);
>                 case var _ when !type.IsAbstract && !type.IsPrimitive: // probably going to need more guards here
>                     return ConvertToEilangInstance(type, obj, factory);
>                 default:
>                     throw new NotImplementedException();
>             }
> ```
> 
> to
> 
> ```cs
>             switch (obj)
>             {
>                 case string s:
>                     return factory.String(s);
>                 case int i:
>                     return factory.Integer(i);
>                 case long l:
>                     return factory.Long(l);
>                 case double d:
>                     return factory.Double(d);
>                 case bool b:
>                     return factory.Bool(b);
>                 case IntPtr ip:
>                     return factory.IntPtr(ip);
>                 default:
>                     var type = obj.GetType();
>                     if (!type.IsAbstract && !type.IsPrimitive) // probably going to need more guards here
>                         return ConvertToEilangInstance(type, obj, factory);
>                     throw new NotImplementedException();
>             }
> ```
> 
> Such a rewrite should also be more performant, as you avoid double type checks in each case.

Thank you for the suggestion, putting the GetType() in the default case makes way more sense :)
