### ISSUE TITLE
LGTM.com - false positive - __asm__ is not handled 

### ISSUE THREAD

**Issue by K2** [Semmle/ql#2595]
**Description of the false positive**

__asm__ is breaking various queries.  Return value tracking should be pretty easy to add. :)

```c
#ifdef IA32_RND
unsigned int get_count()
{
   __asm__("rdtsc");
}
#endif
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/K2/ADMMutate/snapshot/70daec90a876c317b0d873b68f6abb3fdcf3bfd9/files/ADMmuteng.c?sort=name&dir=ASC&mode=heatmap#x5e9b386724327054:1

**Comment by K2** [comment]
# Another example; 

https://lgtm.com/projects/g/K2/ADMMutate/snapshot/70daec90a876c317b0d873b68f6abb3fdcf3bfd9/files/exp.c?sort=name&dir=ASC&mode=heatmap#xa80047b3e6d8d810:1

```c
long get_esp() { __asm__("movl %esp,%eax"); }
```

**Comment by geoffw0** [comment]
Hi @K2,

Analysing assembly language code is beyond the scope of this query, so I've created https://github.com/Semmle/ql/pull/2598 to add an exclusion for functions containing `asm` to the query.  This should resolve the two false positive results you've linked to.

**Comment by geoffw0** [comment]
#2598 has been merged, the fix should be reflected on LGTM within about two weeks.
