### ISSUE TITLE
ER: Filter list of issues by specific type of issue

### ISSUE THREAD

**Issue by ddkilzer** [Semmle/ql#2649]
When looking at a list of issues, I want to be able to filter by a specific type of issue.

Example use cases:

1. Hide all "FIXME comment" issues in a list because I don't care about them and there are too many of them.
2. Show only "Declaration hides parameter" issues because I want to fix all of them.

This request is for filtering a project with a fairly large (over 2k) list of issues:
https://lgtm.com/projects/g/WebKit/webkit/?mode=list

**Comment by ddkilzer** [comment]
The best I can do currently is to filter by specific tags, but I don't see a way to do a logical "and" of two tags to restrict further the list of issues.

**Comment by jbj** [comment]
I always browse alerts with the "group by query" box checked. If you're only interested in the C++ code (rather than the Python build scripts), you can also filter by the C++ language. The result is https://lgtm.com/projects/g/WebKit/webkit/?mode=tree&lang=cpp, which I find to be a great overview.
