### ISSUE TITLE
LGTM.com - false positive: New syntax in TypeScript 3.8

### ISSUE THREAD

**Issue by AlCalzone** [Semmle/ql#2691]
**Description of the false positive**
TypeScript 3.8 will introduce new syntax that is not yet understood by LGTM.com and therefore falsely detected as syntax errors:
* type-only imports
* export * as ns
* EcmaScript private #fields

All details may be found at https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by asgerf** [comment]
TypeScript 3.8 support has been merged. It should go live within a week or two.
