### ISSUE TITLE
regexpMatch doesn't document what regex engine is used

### ISSUE THREAD

**Issue by JLLeitschuh** [Semmle/ql#2693]
None of these explicitly state what regex engine are used to process regexes.

 - https://help.semmle.com/qldoc/java/predicate.string$regexpMatch.1.html
 - https://help.semmle.com/qldoc/cpp/predicate.string$regexpMatch.1.html
 - https://help.semmle.com/qldoc/python/predicate.string$regexpMatch.1.html
 - https://help.semmle.com/qldoc/go/predicate.string$regexpMatch.1.html

As you can see from this table, there are certain features that certain regex engines do/do not support based upon the underlying implementation.
https://en.wikipedia.org/wiki/Comparison_of_regular-expression_engines#Language_features

It would be nice if this were documented in the documentation on the method.

**Comment by esbena** [comment]
Those methods are all on the builtin primitive QL type `string`. 

The documentation for the methods on that type can be found in the language specification here:
https://help.semmle.com/QL/ql-spec/language.html#built-ins-for-string

Just below the table, you have the answer to your question: 

> Regular expressions are as defined by java.util.Pattern in Java.

**Comment by smowton** [comment]
+1: the most efficient route to that documentation is currently:

1. Google codeql regexpmatch
2. Second hit is https://help.semmle.com/qldoc/java/predicate.string$regexpMatch.1.html which doesn't have any useful info
3. Third hit is this issue
4. Follow the link in your comment :)
