### ISSUE TITLE
LGTM.com - false positive - SqlInjectionLib doesn't consider java.lang.Number a sanitization

### ISSUE THREAD

**Issue by JLLeitschuh** [Semmle/ql#2722]
https://github.com/Semmle/ql/blob/79e01a2de56dacba163a4bd5a98163fcb40e35e6/java/ql/src/Security/CWE/CWE-089/SqlInjectionLib.qll#L56-L58

I don't actually have a query that I can link to that finds this because I was working with a custom query when I found this.

It would be appropriate here to consider all conversions to subtypes of `java.lang.Number` a valid sanitization step against SQL injection.

This is what I ended up using:
```ql
private class NumberType extends RefType {
  NumberType() {
    exists(RefType numberType | numberType.hasQualifiedName("java.lang", "Number") and this.extendsOrImplements(numberType))
  }
}
```

Then later:
```ql
  override predicate isSanitizer(DataFlow::Node node) {
    node.getType() instanceof PrimitiveType or
    node.getType() instanceof BoxedType or
    node.getType() instanceof NumberType
  }
```

**Comment by aschackmull** [comment]
Yep, this seems like an easy fix.  I've put up a PR.
