### ISSUE TITLE
LGTM.com - false positive - py/import-own-module

### ISSUE THREAD

**Issue by davfsa** [Semmle/ql#2771]
**Description of the false positive**

From yesterday to today (code wasnt edited) LGTM started giving errors of import own module on `__init__.py` files

**Code to reproduce**

`Project tree`
```
pkg/
  __init__.py
  foo.py
  bar.py
```
`foo.py`
```py
class Foo:
    pass
```

`__init__.py`
```py
from pkg.foo import Foo # Error would be given on this line
```

**URL to the alert on the project page on LGTM.com**

An example of this can be found here: https://lgtm.com/projects/gl/nekokatt/hikari/snapshot/d58690b44effc0473138015613d32df93d352875/files/hikari/__init__.py?sort=name&dir=ASC&mode=heatmap#xd7e23e37c8aecf57:1

**Comment by SimonBoothroyd** [comment]
I've also started seeing this today - an [extra example can be found here](https://lgtm.com/projects/g/openforcefield/openff-evaluator/snapshot/71740029ec0b3f2f31e452f21f0244e68ccd0e75/files/propertyestimator/workflow/__init__.py?sort=name&dir=ASC&mode=heatmap#x8de3ca0123703d89:1)

**Comment by tausbn** [comment]
Thank you all for the reports. We're working on a fix, so this should hopefully go away once the next update on LGTM.com is rolled out. (We just finished one such update, which is why these errors started popping up now. The next one will take place within the next few weeks.)

**Comment by Czaki** [comment]
@tausbn You close this issue? It is fixed?

**Comment by RasmusWL** [comment]
These false positives should go away once the next update on LGTM.com is rolled out, which should happen soon :blush:
