### ISSUE TITLE
C++ IR: FieldAddressInstruction getObjectAddressOperand()

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [Semmle/ql#2798]
In the C++ IR, loads and stores have an operand of type `AddressOperand`, representing the address accessed by that load or store.

The `FieldAddressInstruction` that has an aptly named `getObjectAddressOperand()` predicate.
Unfortunately, this operand is of type `UnaryOperand` instead of `AddressOperand`, although the function of the operand is exactly the same, and even the predicate name indicates it should be of type `AddressOperand`.

I do not understand this design choice.
Furthermore, this design choice makes it more difficult to treat pointer accesses uniformly, as `FieldAddressInstruction`s  need to be specialcased.

**Comment by dbartol** [comment]
`AddressOperand` is only used for the address used to actually access memory, either in a `MemoryOperand` or a memory result in the same `Instruction`. A `FieldAddressInstruction` does not access memory; it only computes an address that may or may not later be used to access memory via an actual `Load` or `Store` instruction. `FieldAddress` is more like a special `PointerAdd` instruction.
I'm open to renaming things to avoid confusion, but I believe the distinction between `AddressOperand` and operands that are not immediately used to dereference memory is critical.

**Comment by Cornelius-Riemenschneider** [comment]
Thank you for your explanation! It makes sense now.

Unfortunately, I can not come up with a different/better name for `getObjectAddressOperand()` right now.
