### ISSUE TITLE
cpp: FPs in Microsoft.SAL

### ISSUE THREAD

**Issue by tosmolka** [Semmle/ql#283]
We noticed false positives when testing SAL annotations. 

These three should demonstrate the issue:
`sal.h:`
```cpp
#define _SAL_VERSION 20
```
`test.cpp:`
```cpp
#include "sal.h"
int method1() {
    return _SAL_VERSION;
}
void method2();
```
`test.ql:`
```cpp
import Microsoft.SAL
from SALAnnotation a
select a, a.getDeclaration()
```
Output from the query:
> | test.cpp:3:12:3:23 | _SAL_VERSION | test.cpp:5:6:5:12 | method2 |

It seems the detection is based on "rank" and the fact that `MacroInvocation _SAL_VERSION` is before `DeclarationEntry method2`. 

Not sure what is the best fix, can you please advise? Thank you.

**Comment by jbj** [comment]
I'll look into this Monday and get back to you.

**Comment by jbj** [comment]
Thanks for the report. I'm working on a fix that I'll try to get out this week. Essentially, I want to break the association of SAL elements not only at start positions of declaration entries but also at end positions of their bodies.

**Comment by jbj** [comment]
I've opened a PR for the fix in the Microsoft-internal repo. When that's merged, it can migrate out to this repo.

**Comment by AlexTereshenkov** [comment]
@tosmolka it's been a year since you've reported this issue. Does the false positive still persist or was it fixed?

**Comment by jbj** [comment]
The fix has finally made it back to this repo (in #2151).
