### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by AlCalzone** [Semmle/ql#2865]
**Description of the false positive**

JavaScript/TypeScript: If the returned `Promise` of an `async` function is explicitly discarded with `void`, it should not be treated as "missing await".

I'm using this pattern in a few places where I know that `await`ing a promise will take a very long time (several hours is likely) under specific circumstances. IMO `void`ing the returned value expresses intent that the promise should not be awaited (rather than simply forgetting the `await`).

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/AlCalzone/node-zwave-js/snapshot/76fa2c870a0c515cc37e422db5628034550232cf/files/src/lib/driver/Driver.ts?sort=name&dir=ASC&mode=heatmap#x623cae70c9600fbc:1

**Comment by asgerf** [comment]
Thanks for report, as always. I agree that this query shouldn't flag `void` operands; I've put up a PR to fix it.

**Comment by AlCalzone** [comment]
fixed by #2868
