### ISSUE TITLE
Error was: Expected result pattern(s) are not present for query kind "Problem"(INVALID_RESULT_PATTERNS)

### ISSUE THREAD

**Issue by 0kk4cce1er** [Semmle/ql#2905]
Describe what i do:

1. 
`git clone https://github.com/Semmle/ql.git ` 
my dir is ~/Github/ql

2.  
touch .config/codeql/config  
content is `--search-path=~/Github/ql`

3.  
cd ~/Github/ql  
cd java/ql/src 
touch test.ql 
```
/**
 * @name Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it
 * @description Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it.
 * @kind problem
 * @problem.severity error
 * @precision high
 * @id java/Random
 * @tags security
 */
import java
import Random

from GetRandomData da,Method m
where m.fromSource() and m.getName().toLowerCase().regexpMatch(".*tok.*")
select da,m,"predictable seed"
```

4. run
```
codeql database analyze --format=sarif-latest --output=~/Tests/  javatest ~/Github/ql/java/ql/src/test.ql 
```
javatest is my database
codeql is the codeql-cli

5. then
```
Running queries.
[1/1] No need to rerun /Users/xxxxx/Github/ql/java/ql/src/test.ql.
Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata.
Error was: Expected result pattern(s) are not present for query kind "Problem"(INVALID_RESULT_PATTERNS).
```

**Comment by tausbn** [comment]
I think the problem may be that your `select` statement does not conform to the [expected form](https://help.semmle.com/QL/learn-ql/writing-queries/select-statement.html), as it is selecting the wrong number of columns. The page I linked describes how to select multiple columns and interpolate them in the alert string.

**Comment by 0kk4cce1er** [comment]
> I think the problem may be that your `select` statement does not conform to the [expected form](https://help.semmle.com/QL/learn-ql/writing-queries/select-statement.html), as it is selecting the wrong number of columns. The page I linked describes how to select multiple columns and interpolate them in the alert string.

ths for reply

i just
cd java/ql/src
mkdir MyQL 
 mv test.ql  MyQL

then run
`
codeql database analyze --format=sarif-latest --output=~/Tests/  javatest ~/Github/ql/java/ql/src/MyQL/test.ql 
`
```
$ codeql database analyze --format=sarif-latest --output=out/1.sarif javatest ~/Github/ql/java/ql/src/MyQL/Test.ql
Running queries.
[1/1] No need to rerun /Users/xxxxx/Github/ql/java/ql/src/MyQL/Test.ql.
Shutting down query evaluator.
Interpreting results.
```
now no error but neither no result.   
1.sarif
```
{
  "$schema" : "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version" : "2.1.0",
  "runs" : [ {
    "tool" : {
      "driver" : {
        "name" : "CodeQL command-line toolchain",
        "organization" : "GitHub",
        "semanticVersion" : "2.0.4",
        "rules" : [ {
          "id" : "java/Random",
          "name" : "java/Random",
          "shortDescription" : {
            "text" : "Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it"
          },
          "fullDescription" : {
            "text" : "Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it."
          },
          "defaultConfiguration" : {
            "level" : "error"
          },
          "properties" : {
            "tags" : [ "security" ],
            "kind" : "problem",
            "precision" : "high",
            "name" : "Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it",
            "description" : "Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it.",
            "id" : "java/Random",
            "problem.severity" : "error"
          }
        } ]
      }
    },
    "results" : [ ],
    "columnKind" : "utf16CodeUnits",
    "properties" : {
      "semmle.formatSpecifier" : "sarif-latest"
    }
  } ]
}
```
What makes me wonder is that execution with VSCode has results

**Comment by 0kk4cce1er** [comment]
> I think the problem may be that your `select` statement does not conform to the [expected form](https://help.semmle.com/QL/learn-ql/writing-queries/select-statement.html), as it is selecting the wrong number of columns. The page I linked describes how to select multiple columns and interpolate them in the alert string.

thx，I may know my mistake

**Comment by m4p1e** [comment]
> > I think the problem may be that your `select` statement does not conform to the [expected form](https://help.semmle.com/QL/learn-ql/writing-queries/select-statement.html), as it is selecting the wrong number of columns. The page I linked describes how to select multiple columns and interpolate them in the alert string.
> 
> thx，I may know my mistake

how u solved that?

**Comment by u2400** [comment]
Hello~ Can you share the solution? @4cce1er

**Comment by wangsanshi123** [comment]
> `select`

The link can't be visited ,could you share a new one ?

**Comment by smowton** [comment]
The relevant docs are now at https://codeql.github.com/docs/writing-codeql-queries/defining-the-results-of-a-query/#adding-a-link-to-the-similar-file
