### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by dlamoris** [Semmle/ql#2939]
**Description of the false positive**

value1 cannot be null because of lines 176-180

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/Open-MBEE/mms-sdvc/snapshot/bd667472362dc6f83d1c2556fc56ca2fa6e2baa2/files/json/src/main/java/org/openmbee/sdvc/json/BaseJson.java?sort=name&dir=ASC&mode=heatmap#x98ae3b5159ad0913:1

**Comment by aschackmull** [comment]
Thank you for your report.  I have added this as a test case in our unit tests, so we can get back to this and fix it when time permits.
