### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by gafderks** [Semmle/ql#2940]
**Description of the false positive**

I'm getting error `py/import-own-module` in an `__init__.py`, which I think is unintentional. I am following the application structure as laid out by the [Django docs](https://docs.djangoproject.com/en/dev/topics/db/models/#organizing-models-in-a-package).

**URL to the alert on the project page on LGTM.com**
[URL](https://lgtm.com/projects/g/gafderks/dbase/snapshot/3d71595351c801cfa212f99103f922ea9fccf7a0/files/booking/models/__init__.py?sort=name&dir=ASC&mode=heatmap)

**Comment by RasmusWL** [comment]
Hi @gafderks, thanks for the report!

This is fixed in https://github.com/Semmle/ql/pull/2802, which should make it to LGTM.com within the next few weeks. Sorry for the inconvenience.
