### ISSUE TITLE
LGTM.com - false positive - Electron - window guard check

### ISSUE THREAD

**Issue by ESWAT** [Semmle/ql#2951]
**Description of the false positive**
LGTM flagged a guard check of `window` in my Electron app, saying this will always evaluate to `false`. This is not true since `window` will be true after a new Electron window is created, but this won't always be the case (app still booting, window is closed, etc.). This check is needed to make sure the app doesn't crash while checking for properties of `window`.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/ESWAT/voidview/snapshot/c54769e0dbb9d7b0f378da51c96bd0501df0caf9/files/src/main/index.js?sort=name&dir=ASC&mode=heatmap#xb9baeacba86bf870:1

**Comment by max-schaefer** [comment]
Thanks for the report, @ESWAT! Can you explain a bit more why this is a false positive? It seems to me that at the point where this expression is evaluated `window` hasn't been initialized yet, and hence is `undefined`, so the condition always evaluates to false.

**Comment by ESWAT** [comment]
Yup you're right, I didn't look closely t my own code about this. Closing.
