### ISSUE TITLE
LGTM.com - false positive - integer comparison - C++

### ISSUE THREAD

**Issue by metrodango** [Semmle/ql#3009]
The warning is as follow (for the three issues):

"Comparison between i of type quint16 and S_ARRAY_SIZE of wider type int."

The code clearly uses static_cast<quint16>() to convert the int to an quint16, moreover the casted value is a constant equal to 256, which is clearly within range for a quint16.

https://lgtm.com/projects/g/metrodango/pip3line/snapshot/e046f7a81f8be6b4517eec1662feb1e17d8c3027/files/defaultplugins/baseplugins/substitution.cpp?sort=name&dir=ASC&mode=heatmap#xa2f279487e9ddbf4:1

https://lgtm.com/projects/g/metrodango/pip3line/snapshot/e046f7a81f8be6b4517eec1662feb1e17d8c3027/files/defaultplugins/baseplugins/substitution.cpp?sort=name&dir=ASC&mode=heatmap#x3bbe3a65dcd32d7c:1

https://lgtm.com/projects/g/metrodango/pip3line/snapshot/e046f7a81f8be6b4517eec1662feb1e17d8c3027/files/defaultplugins/baseplugins/substitution.cpp?sort=name&dir=ASC&mode=heatmap#x890936e77a698943:1

**Comment by MathiasVP** [comment]
Thanks for the report. I'm quite surprised by this result! We'll look into this as soon as possible.

**Comment by jbj** [comment]
The fix has now been merged, and it should get deployed to lgtm.com in about three weeks from now.
