### ISSUE TITLE
LGTM.com - false positive Dead code due to goto or break statement

### ISSUE THREAD

**Issue by sandsmark** [Semmle/ql#3010]
If you have e. g. a loop with a `switch(foo) { case 0: continue; default: if (bar) {  baz(); }` it is flagged as dead code.

https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/src/actions/ActionMove.cpp?sort=name&dir=ASC&mode=heatmap#xfd2d1fb64aab4d2d:1

**Comment by geoffw0** [comment]
I believe this issue is likely to be part of the same thing as https://github.com/Semmle/ql/issues/3012.  As with the other instances, if this particular FP doesn't go away when #3012 is fixed, then please reopen.
