### ISSUE TITLE
LGTM.com - false positive This statement makes ExprStmt unreachable.

### ISSUE THREAD

**Issue by sandsmark** [Semmle/ql#3011]
LGTM in general doesn't seem to enjoy switch statements in c++.

Not really sure why it flags every single case-statement here as unreachable:
https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/src/core/ResourceMap.h#xdfaa351901d06e8e:1 

It's very reachable (and it works...).

**Comment by jbj** [comment]
Thank you for the report. There's something wrong with how we parse the code in your project. Let's use https://github.com/Semmle/ql/issues/3012 as the central place to track the parsing issue. If the particular FPs reported in this issue don't go away when #3012 is fixed, then please reopen.
