### ISSUE TITLE
LGTM.com - false positive Parameter unit hides X Values with the same name.

### ISSUE THREAD

**Issue by sandsmark** [Semmle/ql#3013]
LGTM seems to get confused by namespaces named similarly to parameters:
https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/src/actions/ActionGather.cpp?sort=name&dir=ASC&mode=heatmap#xb49a13678798e2a1:1

https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/extern/genieutils/include/genie/dat/Unit.h?sort=name&dir=ASC&mode=heatmap#x15a494f3a56258ea:1

**Comment by jbj** [comment]
Thank you for the report. There's something wrong with how we parse the code in your project. Let's use https://github.com/Semmle/ql/issues/3012 as the central place to track the parsing issue. If the particular FPs reported in this issue don't go away when #3012 is fixed, then please reopen.
