### ISSUE TITLE
LGTM.com - false positive header guards

### ISSUE THREAD

**Issue by sandsmark** [Semmle/ql#3014]
A couple of different cases.

The FlexLexer one is pretty straight forward bogus, the problem seems to be that it doesn't understand multiple guards in the same file:
https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/extern/FlexLexer.h?sort=name&dir=ASC&mode=heatmap#x64bf2c7c4b8d85aa:1

This seems similar, though a bit more involved. Basically more complex use of guards which is fairly common in e. g. single file c++ libraries:
https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/extern/miniaudio/miniaudio.h?sort=name&dir=ASC&mode=heatmap#xd59b9681c2e6e6c9:1

**Comment by jbj** [comment]
Our analysis for header guards is a bit strict, but it attempts to check for the same conditions as GCC does when applying the _multiple include optimization_: https://gcc.gnu.org/onlinedocs/cppinternals/Guard-Macros.html. Many people are surprised to learn how header-guard discipline can improve compile times in a large project.

Perhaps your project is best served by disabling the header guard check or by ignoring all alerts from the `extern` directory? See https://lgtm.com/help/lgtm/configuring-lgtm-analysis-project.

**Comment by geoffw0** [comment]
Note that internally we have an old ticket https://jira.semmle.com/browse/ODASA-3927 tracking clear and debatable issues with this query.  I've added a reference to this issue from there.  But if you're using non-standard header guard patterns I agree with @jbj that you should just disable the query on your project / part of your project.

**Comment by sandsmark** [comment]
> Many people are surprised to learn how header-guard discipline can improve compile times in a large project.

I'm aware, though I prefer `#pragma once` (been bitten by people typoing the guard name before). :-)


> Perhaps your project is best served by disabling the header guard check or by ignoring all alerts from the extern directory?

My extern/ directory is a bit of a mix of my own and others' libraries, so it's nice to get warnings for my own stuff there at least.

But thanks for the hint about how to disable analysis for certain paths, wasn't aware of that. I try to avoid putting third-party service-specific files in the repo (e. g. keep the appveyor config at appveyor instead of an appveyor.yml), but being able to configure lgtm without adding anything to the git repo is another (fairly minor) issue. :-)


> non-standard header guard patterns
 
FlexLexer.h is just a copy of the official header from upstream GNU Flex (to avoid having to install flex everywhere) and the miniaudio "tricks" are not that uncommon for those kinds of c++ libraries, so while it might be a bit non-standard it's not (very) uncommon.

**Comment by jbj** [comment]
We've seen a couple of projects that have reasonably good reasons to use their own header-guard patterns, but on balance we've decided to keep the check enabled by default since we think it provides value overall.

Thanks for adding to that discussion.

**Comment by jbj** [comment]
[I'm trying to close the issue, but GitHub wouldn't let me. Trying again.]
