### ISSUE TITLE
LGTM.com - false positive Unused variable colors

### ISSUE THREAD

**Issue by bkimminich** [Semmle/ql#3018]
**Description of the false positive**

The `Unused variable colors.` warning when importing https://www.npmjs.com/package/colors in order to utilize its prototype extension of `String` is a false positive. ESLint and other tools have the same issue, because it's not obvious how this works. Here's a quote from the https://www.npmjs.com/package/colors documentation:

> By popular demand, colors now ships with two types of usages!
>
> The super nifty way
> 
> ```
> var colors = require('colors');
> 
> console.log('hello'.green); // outputs green text
> console.log('i like cake and pies'.underline.red) // outputs red underlined text
> console.log('inverse the color'.inverse); // inverses the color
> console.log('OMG Rainbows!'.rainbow); // rainbow
> console.log('Run the trap'.trap); // Drops the bass
> ```

**URL to the alert on the project page on LGTM.com**

<https://lgtm.com/projects/g/bkimminich/juice-shop-ctf/snapshot/f35af62c19dd5cf1286481711255eb9288b6834e/files/index.js?sort=name&dir=ASC&mode=heatmap#x81216c7052240c2c:1>

**Comment by asgerf** [comment]
Hi bkimminich,

Thanks for the report. I believe the alert is correct in this case, as it is indeed safe to remove the unused variable and instead write:
```js
require('colors');
```
