### ISSUE TITLE
LGTM.com - false positive?: Mismatching new/free or malloc/delete: Placement new

### ISSUE THREAD

**Issue by intrigus-lgtm** [Semmle/ql#3028]
**Description of the false positive**
Lgtm reports a mismatch between new and free.
However in this case I think there is no mismatch, since the object is allocated using placement new. And the memory used for it is allocated using `calloc` so it should also be freed using `free`, right?

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/WohlSoft/PGE-Project/snapshot/86d5fb85ebb2df866ae321c754da956bc584687d/files/_Libs/AudioCodecs/libOPNMIDI/src/chips/np2_opna.cpp?sort=name&dir=ASC&mode=heatmap#x57a58d2701ff6548:1

**Comment by geoffw0** [comment]
Yes - the query doesn't currently understand placement new and is supposed to just exclude them.  It looks like something's gone wrong with that, I'll look into it.

**Comment by geoffw0** [comment]
There's now a fix for this issue in the works (it turns out we already excluded placement new, but the exclusion didn't work correctly in templates).
