### ISSUE TITLE
Why can't SqlTainted.ql analyze header injection and cookie injection?

### ISSUE THREAD

**Issue by niuzhi** [Semmle/ql#3077]
1.Why can't SqlTainted.ql analyze header injection and cookie injection?
2.How to print the remote input stream in the program. For example, there is a RemoteFlowSource class in ql. How do I check which remote input streams are in my program, that is, print out all the information related to RemoteFlowSource.

ForExample：
/**
* OWASP Benchmark v1.2
*
* This file is part of the Open Web Application Security Project (OWASP)
* Benchmark Project. For details, please see
* <a href="https://www.owasp.org/index.php/Benchmark">https://www.owasp.org/index.php/Benchmark</a>.
*
* The OWASP Benchmark is free software: you can redistribute it and/or modify it under the terms
* of the GNU General Public License as published by the Free Software Foundation, version 2.
*
* The OWASP Benchmark is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* @author Dave Wichers <a href="https://www.aspectsecurity.com">Aspect Security</a>
* @created 2015
*/
package org.owasp.benchmark.testcode;
import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
@WebServlet(value="/sqli-00/BenchmarkTest00008")
public class BenchmarkTest00008 extends HttpServlet {
	private static final long serialVersionUID = 1L;
	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
	}
	@Override
	public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// some code
		response.setContentType("text/html;charset=UTF-8");
		String param = "";
		if (request.getHeader("BenchmarkTest00008") != null) {
			param = request.getHeader("BenchmarkTest00008");
		}
		// URL Decode the header value since req.getHeader() doesn't. Unlike req.getParameter().
		param = java.net.URLDecoder.decode(param, "UTF-8");
		String sql = "{call " + param + "}";		
		try {
			java.sql.Connection connection = org.owasp.benchmark.helpers.DatabaseHelper.getSqlConnection();
			java.sql.CallableStatement statement = connection.prepareCall( sql );
		    java.sql.ResultSet rs = statement.executeQuery();
            org.owasp.benchmark.helpers.DatabaseHelper.printResults(rs, sql, response);
		} catch (java.sql.SQLException e) {
			if (org.owasp.benchmark.helpers.DatabaseHelper.hideSQLErrors) {
        		response.getWriter().println(
"Error processing request."
);
        		return;
        	}
			else throw new ServletException(e);
		}
	}
}

**Comment by aschackmull** [comment]
The `SqlTainted.ql` query tracks flow from sources in `RemoteFlowSource`.  You can see what those sources are by running the following query:
```
import java
import semmle.code.java.dataflow.FlowSources

from RemoteFlowSource source
select source
```

**Comment by niuzhi** [comment]
> The `SqlTainted.ql` query tracks flow from sources in `RemoteFlowSource`. You can see what those sources are by running the following query:
> 
> ```
> import java
> import semmle.code.java.dataflow.FlowSources
> 
> from RemoteFlowSource source
> select source
> ```

**Comment by niuzhi** [comment]
@aschackmull 
Thanks.
I checked the source and sink。
source：
![image](https://user-images.githubusercontent.com/33443724/76837574-bffd6480-686d-11ea-9fb1-9a07e3e85c50.png)
Sink:
![image](https://user-images.githubusercontent.com/33443724/76837744-06eb5a00-686e-11ea-8622-dd581d1fccd5.png)

Why can't I check it out?
TaintTracking::Configuration code：
![image](https://user-images.githubusercontent.com/33443724/76837994-72cdc280-686e-11ea-85c2-c3dd76ea8489.png)
