### ISSUE TITLE
Why can't SqlTainted.ql analyze header injection and cookie injection?  java

### ISSUE THREAD

**Issue by niuzhi** [Semmle/ql#3079]
@aschackmull 
Thanks.
I checked the source and sink。
source：
![image](https://user-images.githubusercontent.com/33443724/76837574-bffd6480-686d-11ea-9fb1-9a07e3e85c50.png)
Sink:
![image](https://user-images.githubusercontent.com/33443724/76837744-06eb5a00-686e-11ea-8622-dd581d1fccd5.png)

Why can't I check it out?
TaintTracking::Configuration code：
![image](https://user-images.githubusercontent.com/33443724/76837994-72cdc280-686e-11ea-85c2-c3dd76ea8489.png)

**Comment by aschackmull** [comment]
It appears that we're missing a taint step through `URLDecoder.decode`.  Thanks for flagging this.  I've added a PR to fix this here: https://github.com/Semmle/ql/pull/3081.  In the meantime you can add the following additional step:
```
override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
  exists(MethodAccess ma, Method m |
    ma.getMethod() = m and m.getDeclaringType().hasQualifiedName("java.net", "URLDecoder") and
    m.getName() = "decode" and
    node1.asExpr() = ma.getArgument(0) and
    node2.asExpr() = ma
  )
}
```
In general you can debug missing steps by overriding the `explorationLimit()` predicate on configurations:
```
/**
   * Gets the exploration limit for `hasPartialFlow` measured in approximate
   * number of interprocedural steps.
   */
  int explorationLimit() { none() }

  /**
   * Holds if there is a partial data flow path from `source` to `node`. The
   * approximate distance between `node` and the closest source is `dist` and
   * is restricted to be less than or equal to `explorationLimit()`. This
   * predicate completely disregards sink definitions.
   *
   * This predicate is intended for dataflow exploration and debugging and may
   * perform poorly if the number of sources is too big and/or the exploration
   * limit is set too high without using barriers.
   *
   * This predicate is disabled (has no results) by default. Override
   * `explorationLimit()` with a suitable number to enable this predicate.
   *
   * To use this in a `path-problem` query, import the module `PartialPathGraph`.
   */
  final predicate hasPartialFlow(PartialPathNode source, PartialPathNode node, int dist) {
    partialFlow(source, node, this) and
    dist = node.getSourceDistance()
  }
}
```

**Comment by niuzhi** [comment]
@aschackmull 
Can you share with me the use case of this function？explorationLimit。
thank you very much！

**Comment by aschackmull** [comment]
Its use is documented in the qldoc sections I quoted.  Basically, starting from a query you're developing with a configuration you'd like to debug, you then add `override in explorationLimit() { result = 5 }` (or some other suitable number, depending on your use case).  With that in place you can use `hasPartialFlow` instead of `hasFlow` to see all the places your sources reach.

**Comment by niuzhi** [comment]
@aschackmull thanks.
I use explorationLimit function，why dist is zero? can you help me,thanks very much
![image](https://user-images.githubusercontent.com/33443724/76921474-1ec3ec00-6909-11ea-9a58-91bc9a0d6810.png)

**Comment by niuzhi** [comment]
@aschackmull  Demno:
/**
* OWASP Benchmark Project v1.2
*
* This file is part of the Open Web Application Security Project (OWASP)
* Benchmark Project. For details, please see
* <a href="https://www.owasp.org/index.php/Benchmark">https://www.owasp.org/index.php/Benchmark</a>.
*
* The OWASP Benchmark is free software: you can redistribute it and/or modify it under the terms
* of the GNU General Public License as published by the Free Software Foundation, version 2.
*
* The OWASP Benchmark is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* @author Dave Wichers <a href="https://www.aspectsecurity.com">Aspect Security</a>
* @created 2015
*/

package org.owasp.benchmark.testcode;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(value="/sqli-02/BenchmarkTest01006")
public class BenchmarkTest01006 extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
	
	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		javax.servlet.http.Cookie userCookie = new javax.servlet.http.Cookie("BenchmarkTest01006", "bar");
		userCookie.setMaxAge(60*3); //Store cookie for 3 minutes
		userCookie.setSecure(true);
		userCookie.setPath(request.getRequestURI());
		response.addCookie(userCookie);
		javax.servlet.RequestDispatcher rd = request.getRequestDispatcher("/sqli-02/BenchmarkTest01006.html");
		rd.include(request, response);
	}

	@Override
	public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
	
		javax.servlet.http.Cookie[] theCookies = request.getCookies();
		
		String param = "noCookieValueSupplied";
		if (theCookies != null) {
			for (javax.servlet.http.Cookie theCookie : theCookies) {
				if (theCookie.getName().equals("BenchmarkTest01006")) {
					param = java.net.URLDecoder.decode(theCookie.getValue(), "UTF-8");
					break;
				}
			}
		}

		String bar = new Test().doSomething(request, param);
		
		String sql = "SELECT TOP 1 userid from USERS where USERNAME='foo' and PASSWORD='" + bar + "'";
		try {
			Long results = org.owasp.benchmark.helpers.DatabaseHelper.JDBCtemplate.queryForLong(sql);
			response.getWriter().println(
				"Your results are: "
			);

	//		System.out.println("your results are");
			response.getWriter().println(
				results.toString()
			);
	//		System.out.println(results);
		} catch (org.springframework.dao.EmptyResultDataAccessException e) {
			response.getWriter().println(
				"No results returned for query: " + org.owasp.esapi.ESAPI.encoder().encodeForHTML(sql) 
			);
		} catch (org.springframework.dao.DataAccessException e) {
			if (org.owasp.benchmark.helpers.DatabaseHelper.hideSQLErrors) {
        		response.getWriter().println(
					"Error processing request."
				);
        	}
			else throw new ServletException(e);
		}
	}  // end doPost

	
    private class Test {

        public String doSomething(HttpServletRequest request, String param) throws ServletException, IOException {

		String bar = "safe!";
		java.util.HashMap<String,Object> map36088 = new java.util.HashMap<String,Object>();
		map36088.put("keyA-36088", "a-Value"); // put some stuff in the collection
		map36088.put("keyB-36088", param); // put it in a collection
		map36088.put("keyC", "another-Value"); // put some stuff in the collection
		bar = (String)map36088.get("keyB-36088"); // get it back out

            return bar;
        }
    } // end innerclass Test

} // end DataflowThruInnerClass

**Comment by aschackmull** [comment]
Qldoc for `explorationLimit` says
> Gets the exploration limit for `hasPartialFlow` measured in approximate number of interprocedural steps.

and qldoc for `hasPartialFlow` says
> The approximate distance between `node` and the closest source is `dist` and is restricted to be less than or equal to `explorationLimit()`.

I guess it could be a bit clearer, but as it says, `dist` is the distance to a source measured in approximate number of interprocedural steps, i.e. if everything is in the same method the `dist` is 0.

**Comment by niuzhi** [comment]
@aschackmull thanks 
1.TaintTrackingUtil.qll not existsorg.apache.commons.codec.binary.Base64 method taint step，please add。
![image](https://user-images.githubusercontent.com/33443724/76936841-98ba9c00-692e-11ea-96ec-b48cef51c32d.png)
2.why not SqlTainted.ql not check this example？
![image](https://user-images.githubusercontent.com/33443724/76937424-c0f6ca80-692f-11ea-8480-65de2a640456.png)

**Comment by aschackmull** [comment]
At a guess we might be missing the `queryForLong` method call as an sql sink.  Checking with a simple query to see whether you can find the expected sinks without requiring flow is a good way to debug something like this:
```
from QueryInjectionSink sink
select sink
```

**Comment by niuzhi** [comment]
@aschackmull 
This is not queryForLong question.Because I can obtain sink.
String bar = new Test().doSomething(request, param);problem。
please help me。Thank you very much。
![image](https://user-images.githubusercontent.com/33443724/76955799-cfec7580-694d-11ea-854b-14809fc09f06.png)

**Comment by niuzhi** [comment]
@aschackmull 
I have solved it, thanks
