### ISSUE TITLE
Java: Do not require that FinalizeMethod is protected

### ISSUE THREAD

**Issue by Marcono1234** [Semmle/ql#3103]
The CodeQL class `FinalizeMethod` currently requires that the method is `protected`, however subclasses can increase its visibility to `public`.
https://github.com/Semmle/ql/blob/16f29570291e3560185ae676491a89360cc2933d/java/ql/src/semmle/code/java/Member.qll#L490

Would it be possible to remove that requirement?

**Comment by aschackmull** [comment]
Yep. I've put up a PR.
