### ISSUE TITLE
Java: LambdaExpr.getStmtBody() should return Block, not Stmt

### ISSUE THREAD

**Issue by Marcono1234** [Semmle/ql#3104]
`LambdaExpr.getStmtBody()` returns `Stmt`, however the type is actually `Block` (as returned by `Method.getBody()`), see here:
https://github.com/Semmle/ql/blob/16f29570291e3560185ae676491a89360cc2933d/java/ql/src/semmle/code/java/Expr.qll#L1019

Therefore `getStmtBody()` should return `Block`. Currently you would have to write `getStmtBody().(Block)` which is rather inconvenient.

**Comment by aschackmull** [comment]
Yes, that's an easy improvement.  I've put up a PR.
