### ISSUE TITLE
What is the equivalent of CallExpr in Python? 

### ISSUE THREAD

**Issue by imanoracle** [Semmle/ql#3167]
Hi there,

I want to convert the following query (from Javascript to Python), but I cannot find CallExpr equivalent in Python (My source is a get function from any classes and my sink is execute function of sqlite3 cursor).

```
import javascript

class XSSTracker extends TaintTracking::Configuration {
  XSSTracker() {
    // unique identifier for this configuration
    this = "XSSTracker"
  }
  override predicate isSource(DataFlow::Node nd) {
   exists(CallExpr dollarCall |
      nd.asExpr() instanceof CallExpr and
      dollarCall.getCalleeName() = "get" and
      nd.asExpr() = dollarCall
    ) 
  }
  override predicate isSink(DataFlow::Node nd) {
    exists(CallExpr dollarCall |
      dollarCall.getCalleeName() = "execute" and
      nd.asExpr() = dollarCall.getArgument(0)
    )
  }
}
from XSSTracker pt, DataFlow::Node source, DataFlow::Node sink
where pt.hasFlow(source, sink)
select source,sink
```

**Comment by RasmusWL** [comment]
In python the AST node for a function call is `Call`.

I can strongly recommend checking out our Python documentation: https://help.semmle.com/QL/learn-ql/python/ql-for-python.html

In essence, what you end up with is something like the following:

```codeql
class XSSTracker extends TaintTracking::Configuration {
    predicate isSource(DataFlow::Node src, TaintKind kind) {
        exsits(Call call |
            src.asAstNode() = ...
        )
    }
}
```

**Comment by imanoracle** [comment]
Thanks for the answer, but why it doesn't return anything for a simple query like this?
(for this code `https://github.com/imanoracle/vulnerable/blob/master/ansible/roles/api/files/vAPI.py`)
```
import python
from Call c
where c.toString().matches("%execute%")
select c
```

**Comment by RasmusWL** [comment]
The code you're looking for is

```codeql
from Call c
where
    c.getLocation().getFile().getShortName() = "vAPI.py" and
    c.getFunc().(Attribute).getName() = "execute"
select c
```

Note that this will get you ALL calls to anything named `execute`, also `nothing_to_do_with_sql.execute()`.

It should have been possible to use the following code, but our points-to analysis currently doesn't figure out that `c` is an instance of `sqlite3.Cursor` after `conn = sqlite3.connect(); c = conn.cursor()` :disappointed: 

```
select Value::named("sqlite3.Cursor").(ClassValue).lookup("execute").getACall()
```

---

Just as a FYI you should never use `toString()` to filter results in your query, since how we formatting values is an internal implementation detail that could be changed at any time. It's perfectly fine to use in your select though.

**Comment by imanoracle** [comment]
Thank you.

**Comment by RasmusWL** [comment]
I just realized that you opened #2961, and it's very cool to see that you're probably trying to add this feature yourself :+1: 

If you didn't already, you can have a look at https://github.com/Semmle/ql/blob/master/python/ql/src/Security/CWE-089/SqlInjection.ql which is the implementation for the `py/sql-injection` query.

In [semmle.python.security.injection.Sql](https://github.com/Semmle/ql/blob/master/python/ql/src/semmle/python/security/injection/Sql.qll) we define the abstract class [DbCursor](https://github.com/Semmle/ql/blob/ca9b892519f0f3c24cf67073fbe4de3bc3f6a890/python/ql/src/semmle/python/security/injection/Sql.qll#L38-L47) that is used to [define a `SqlInjectionSink`](https://github.com/Semmle/ql/blob/master/python/ql/src/semmle/python/security/injection/Sql.qll#L67-L83).

The logic for adding support for django can be seen in https://github.com/Semmle/ql/blob/master/python/ql/src/semmle/python/web/django/Db.qll#L4-L27

**Comment by imanoracle** [comment]
There are 10 different bugs in that file but LGTM can only detect one of them (code injection) and it doesn't detect the others (such as Regex DDoS, IDOR, SQL Injection, ...). 

Thank you for your help.

Best,
Iman

**Comment by RasmusWL** [comment]
Also, if you haven't seen it already @imanoracle , you should check out https://securitylab.github.com/get-involved -- we currently run a slack instance where it might be easier to ask one-off questions about CodeQL :blush:

**Comment by imanoracle** [comment]
Awesome, you're doing a great job. I found dozens of security bugs in Linux source code using CodeQL, but I didn't report them. For example:

On line 90 of [https://github.com/torvalds/linux/blob/master/tools/lib/subcmd/help.c](https://github.com/torvalds/linux/blob/master/tools/lib/subcmd/help.c)
"`ws->ws_col = atoi(s)`" there is a chance of integer overflow, if the user provide a large value for COLUMNS environment variable.

**Comment by RasmusWL** [comment]
> There are 10 different bugs in that file but LGTM can only detect one of them (code injection) and it doesn't detect the others (such as Regex DDoS, IDOR, SQL Injection, ...).

Yep, we still have some work to do :stuck_out_tongue: implementing a ReDoS query in on my list of things to do, but haven't had time yet.

If you're not aware, we're currently running a bounty program for writing CodeQL queries (https://securitylab.github.com/bounties) -- I'm not 100% how improving existing queries is covered, but it might be of interest to you anyway :blush:

**Comment by imanoracle** [comment]
Thank you for your help.

**Comment by imanoracle** [comment]
@RasmusWL Hi Rasmus, sorry for asking basic questions! Why it does not catch that [SQL injection](https://github.com/imanoracle/vulnerable/blob/master/ansible/roles/api/files/vAPI.py#L147-L160)? (I know the query is too general and might catch many false-positives, but it does not catch anything right now!)

`import python
import semmle.python.security.Paths
/* Sources */
import semmle.python.web.HttpRequest
/* Sinks */

class SimpleTest extends TaintKind {
    SimpleTest() { this = "simple test" }
}

class SimpleSink extends TaintSink {
    override string toString() { result = "Simple sink" }

    SimpleSink() {
        exists(Call c | c.getFunc().(Attribute).getName() = "execute")
    }

    override predicate sinks(TaintKind taint) { taint instanceof SimpleTest }
}
    

class SQLInjectionConfiguration extends TaintTracking::Configuration {
    SQLInjectionConfiguration() { this = "SQL injection configuration" }

    override predicate isSource(TaintTracking::Source source) {
        source instanceof HttpRequestTaintSource
    }

    override predicate isSink(TaintTracking::Sink sink) { sink instanceof SimpleSink }
}

from SQLInjectionConfiguration config, TaintedPathSource src, TaintedPathSink sink
where config.hasFlowPath(src, sink)
select sink.getSink(), src, sink, "This SQL query depends on $@.", src.getSource(),
    "a user-provided value"`

**Comment by imanoracle** [comment]
@RasmusWL Hi Rasmus, sorry for asking basic questions! Why it does not catch that [SQL injection](https://github.com/imanoracle/vulnerable/blob/master/ansible/roles/api/files/vAPI.py#L147-L160)? (I know the query is too general and might catch many false-positives, but it does not catch anything right now!)

```
import python
import semmle.python.security.Paths
import semmle.python.web.HttpRequest


class SimpleTest extends TaintKind {
    SimpleTest() { this = "simple test" }
}

class SimpleSink extends TaintSink {
    override string toString() { result = "Simple sink" }

    SimpleSink() {
        exists(Call c | c.getFunc().(Attribute).getName() = "execute")
    }

    override predicate sinks(TaintKind taint) { taint instanceof SimpleTest }
}
    

class SQLInjectionConfiguration extends TaintTracking::Configuration {
    SQLInjectionConfiguration() { this = "SQL injection configuration" }

    override predicate isSource(TaintTracking::Source source) {
        source instanceof HttpRequestTaintSource
    }

    override predicate isSink(TaintTracking::Sink sink) { sink instanceof SimpleSink }
}

from SQLInjectionConfiguration config, TaintedPathSource src, TaintedPathSink sink
where config.hasFlowPath(src, sink)
select sink.getSink(), src, sink, "This SQL query depends on $@.", src.getSource(),
    "a user-provided value"

```

**Comment by RasmusWL** [comment]
The problem is that you're not restricting what `this` can be in the characteristic predicate for `SimpleSink`. To make the 0'th argument of any call to "execute" a sink, we need to do this:

```codeql
    SimpleSink() {
        exists(Call c |
            c.getFunc().(Attribute).getName() = "execute" and
            c.getArg(0) = this.(ControlFlowNode).getNode()
        )
    }
```

**Comment by RasmusWL** [comment]
> sorry for asking basic questions!

Don't worry about it, QL is a bit tricky, and it takes a good deal of time and effort to learn! (I'm still on that path)

**Comment by imanoracle** [comment]
Thank you for your prompt responses, Still it does not catch that [part ](https://github.com/imanoracle/vulnerable/blob/master/ansible/roles/api/files/vAPI.py#L147-L160)of the code (it returns zero results). Do I miss something else?

```
import python
import semmle.python.security.Paths
import semmle.python.web.HttpRequest


class SimpleTest extends TaintKind {
    SimpleTest() { this = "simple test" }
}

class SimpleSink extends TaintSink {
    override string toString() { result = "Simple sink" }

    SimpleSink() {
        exists(Call c |
            c.getFunc().(Attribute).getName() = "execute" and
            c.getArg(0) = this.(ControlFlowNode).getNode()
        )
    }

    override predicate sinks(TaintKind taint) { taint instanceof SimpleTest }
}
    

class SQLInjectionConfiguration extends TaintTracking::Configuration {
    SQLInjectionConfiguration() { this = "SQL injection configuration" }

    override predicate isSource(TaintTracking::Source source) {
        source instanceof HttpRequestTaintSource
    }

    override predicate isSink(TaintTracking::Sink sink) { sink instanceof SimpleSink }
}

from SQLInjectionConfiguration config, TaintedPathSource src, TaintedPathSink sink
where config.hasFlowPath(src, sink)
select sink.getSink(), src, sink, "This SQL query depends on $@.", src.getSource(),
    "a user-provided value"
```

**Comment by RasmusWL** [comment]
The main problem is in your sink:

```codeql
override predicate sinks(TaintKind taint) { taint instanceof SimpleTest }
```

This says that any value that ends up in the `vuln` part of `<something>.execute(vuln)` is a problem **if and only if it is tainted with `SimpleTest`**. Instead, what you are actually looking for is something that is tainted with `ExternalStringKind` (a string that is controlled by a user). 

_I could probably have spotted that earlier, but I tend to work as an old-school compiler that stops after finding the first problem_

### Problems in bottle modeling

You're still not going to get any results after fixing this, but that's because the modeling of bottle is not complete. There are 2 problems, that I will make a PR that fixes tomorrow:

- We currently don't understand wildcards with filters, so we don't understand that the `user` parameter of `get_user` will be controlled by a user.
- We currently don't treat the result of `request.headers.get('X-Auth-Token')` as being tainted (with `ExternalStringKind`).

Will update tomorrow once I land the PR, with steps so you can continue exploring locally.

**Comment by imanoracle** [comment]
Thank you.

**Comment by RasmusWL** [comment]
Sadly, I had to focus on some other things today. I'll get back to you early next week.

**Comment by RasmusWL** [comment]
@imanoracle there is a PR for improving modeling of bottle now (#3267).

To use it, you need to run your queries locally on your machine. First follow the instruction from https://securitylab.github.com/tools/codeql about setting up the VS Code extension and [the CodeQL starter workspace](https://github.com/github/vscode-codeql-starter/).

Then 
```sh
$ cd <some/path>/vscode-codeql-starter/ql
$ git checkout -b RasmusWL-python-proper-bottle-modeling master
$ git pull git://github.com/RasmusWL/ql.git python-proper-bottle-modeling
```

Now your checkout of QL has the changes I made in that PR, and if you fix the `sinks` predicate on `SimpleSink` and run your query, you should start seeing some more results :+1:

**Comment by imanoracle** [comment]
@RasmusWL Thank you very much! I'll do that. Do you know when it would be available on LGTM?

**Comment by RasmusWL** [comment]
Once the PR is merged it usually goes live on LGTM.com within 2-3 weeks.

**Comment by imanoracle** [comment]
Hi @RasmusWL 
I was busy on working on other projects. Today, I've checked my query on LGTM, still it doesn't catch anything for me
```
import python
import semmle.python.security.Paths
import semmle.python.web.HttpRequest



class SimpleSink extends TaintSink {
    override string toString() { result = "Simple sink" }

    SimpleSink() {
        exists(Call c |
            c.getFunc().(Attribute).getName() = "execute" and
            c.getArg(0) = this.(ControlFlowNode).getNode()
        )
    }

    override predicate sinks(TaintKind taint) { taint instanceof ExternalStringKind }
}
    

class SQLInjectionConfiguration extends TaintTracking::Configuration {
    SQLInjectionConfiguration() { this = "SQL injection configuration" }

    override predicate isSource(TaintTracking::Source source) {
        source instanceof HttpRequestTaintSource
    }

    override predicate isSink(TaintTracking::Sink sink) { sink instanceof SimpleSink }
}

from SQLInjectionConfiguration config, TaintedPathSource src, TaintedPathSink sink
where config.hasFlowPath(src, sink)
select sink.getSink(), src, sink, "This SQL query depends on $@.", src.getSource(),
    "a user-provided value"
```
Also, I tried it on CodeQL CLI and I'm getting dependency errors, do you have any idea how can I fix this too?
```
C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\pythonCode>codeql database analyze testRule C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql --format=csv --output=testQuery.csv
Running queries.
Compiling query plan for C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql.
ERROR: Could not resolve module semmle.python.security.Paths. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:2,8-36)
ERROR: Could not resolve module semmle.python.web.HttpRequest. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:3,8-37)
ERROR: Could not resolve module python. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:1,8-14)
ERROR: Could not resolve type TaintSink (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:7,26-35)
ERROR: Could not resolve type Call (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:11,16-20)
ERROR: Could not resolve type Attribute (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:12,26-35)
ERROR: Could not resolve type ControlFlowNode (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:13,33-48)
ERROR: Could not resolve type TaintKind (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:17,30-39)
ERROR: Could not resolve type ExternalStringKind (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:17,66-84)
ERROR: Could not resolve module TaintTracking. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:21,41-54)
ERROR: Could not resolve module TaintTracking. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:24,33-46)
ERROR: Could not resolve type HttpRequestTaintSource (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:25,27-49)
ERROR: Could not resolve module TaintTracking. There should probably be a qlpack.yml file declaring dependencies in C:\Users\MYUSER\Documents\MYNAME\CodeQLNew or an enclosing directory. (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:28,31-44)
ERROR: Could not resolve type TaintedPathSource (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:31,40-57)
ERROR: Could not resolve type TaintedPathSink (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:31,63-78)
ERROR: hasFlowPath(<unknown>, <unknown>) cannot be resolved for type SQLInjectionConfiguration (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:32,14-25)
ERROR: This predicate does not override another predicate (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:8,5-58)
ERROR: This predicate does not override another predicate (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:17,5-86)
ERROR: SQLInjectionConfiguration must implement toString() (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:21,7-32)
ERROR: This predicate does not override another predicate (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:24,5-26,6)
ERROR: This predicate does not override another predicate (C:\Users\MYUSER\Documents\MYNAME\CodeQLNew\test.ql:28,5-87)
```
Thanks for your time!

**Comment by RasmusWL** [comment]
Hi @imanoracle . So the PR still hasn't been merged, since it unveiled a fundamental problem in the way we modeled taint of libraries. It has not been a top priority to fix since we're trying to realign our libraries to match what other languages are doing. Hopefully that will also allow us to do modeling more easily in the future :wink:

**Comment by imanoracle** [comment]
Thank you @RasmusWL ! Is there any trick to achieve approximately the same result using the current CodeQL that we have?

**Comment by RasmusWL** [comment]
Not really besides checking out a copy of my PR as we discussed above. The problem we uncovered means that we can't put it in production in general, but for running it against a single code-base like yours it should be fine.

If you just want it to work on LGTM.com, you can always rewrite your example code to use the parts of flask that is supported by our current library models on the main/master branch.
