### ISSUE TITLE
LGTM.com - false positive in comparison

### ISSUE THREAD

**Issue by mgrabovsky** [Semmle/ql#3174]
**Description of the false positive**

In this chunk of code, `y` can (and does) demonstrably attain values larger than 1000.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/abrt/faf/snapshot/727b60316457495e8d5791f69943e9b4f07bed85/files/src/webfaf/static/js/custom.js#x23e2c3c6a75f1d30:1

**Comment by intrigus-lgtm** [comment]
Doesn't https://lgtm.com/projects/g/abrt/faf/snapshot/727b60316457495e8d5791f69943e9b4f07bed85/files/src/webfaf/static/js/custom.js?sort=name&dir=ASC&mode=heatmap#L265
````javascript
if (y >= 1_000_000) {
return ...
}
if(y >= 1_000)
````
 prevent reaching the `y >= 1_000` condition?

**Comment by mgrabovsky** [comment]
No, it doesn't. `y` can be an arbitrary number, as far as the function is concerned.

**Comment by intrigus-lgtm** [comment]
Disregard my earlier comment, in my mind I switched the conditions around.
Then the alert would have made sense.

**Comment by asgerf** [comment]
Hi mgrabovsky,

Thanks for the report. It was due to a bug in our parser when dealing with underscores in numberic literals. I've landed a fix now which should go live in a few weeks.
