### ISSUE TITLE
LGTM doesn't remove checks when all source files of a particular language are deleted

### ISSUE THREAD

**Issue by fubuloubu** [Semmle/ql#3175]
I added LGTM.com when my Python project had one JS file I used for testing, therefore it added both the Python and JS checks. I have since deleted the JS file, but LGTM never removed the check. I've tried re-registering, different settings on LGTM.com, and everything I can think of. There doesn't seem to be a way of removing a particular language that you don't want checks done for.

In general, it should be possible to configure which languages you want, and specifically it should probably just remove ones where no files of that language exist anymore (if possible)

**Comment by RasmusWL** [comment]
Hi @fubuloubu, could you please add a link to the project? :blush:

**Comment by fubuloubu** [comment]
https://lgtm.com/projects/g/vyperlang/vyper/

**Comment by RasmusWL** [comment]
We've turned off JavaScript analysis for that project, so _LGTM analysis: JavaScript_ should no longer show up as a check in new Pull Requests.

The build history will unfortunately always show JavaScript as in-progress and some JavaScript files may still show in the files tab but hopefully that's less annoying than PR integration failing.

**Comment by fubuloubu** [comment]
Thank you! That works for me!

More broadly, it would be nice not to have to manually ask for this, but at least there is awareness that this scenario can happen.

**Comment by RasmusWL** [comment]
No problem. Glad we could help out :+1:
