### ISSUE TITLE
LGTM.com - false positive ( 1 bit long integer bitfield)

### ISSUE THREAD

**Issue by michael-dev** [Semmle/ql#3187]
**Description of the false positive**

LGTM warns of ambigously signed integer bit field.
Though, the integer bit field here is only 1 bit long, so there is no real ambiguity?

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/michael-dev/mvrpd/snapshot/06fbead9bbbfce625a8c29b5b852dabb7f6685b5/files/src/mvrp.c#xa4df9c7c38b79f40:1

**Comment by jbj** [comment]
If the compiler makes the bitfield signed, then the two possible values are `0` and `-1`. Many programmers might expect it to be `0` and `1`, and this could result in bugs that come and go depending on the compiler.

Here's an example program that shows this behaviour under GCC: https://godbolt.org/z/WSUhby

I'll close the issue. Feel free to reopen if I've misunderstood what you meant.

**Comment by michael-dev** [comment]
Convinced, thanks !
