### ISSUE TITLE
LGTM.com - false positive - C# useless-assignment-to-local value actually returned

### ISSUE THREAD

**Issue by gfs** [Semmle/ql#3305]
### Issue Detected by LGTM
`useless-assignment-to-local` for `fileName` on line 55.

### Problem with this detection
`fileName` is actually returned on line 63.

### Link to issue
https://lgtm.com/projects/g/microsoft/DevSkim/snapshot/1c08d82fce79b2a628f17791738ca20959f1e427/files/src/Microsoft.DevSkim/Microsoft.DevSkim.CLI/ExceptionLogger.cs#x164eb12fa2038f2d:1

**Comment by hvitved** [comment]
Thank you very much for reporting this. Turns out that this was caused by a bug in our control-flow graph construction.
