### ISSUE TITLE
False positives + query ideas for variables with leading underscores.

### ISSUE THREAD

**Issue by samlanning** [Semmle/ql#655]
`js/unused-local-variable` has some false positives for variables that are intentionally unused, e.g. for array destructuring, etc...

An example can be seen in https://github.com/Shopify/quilt/pull/434

It's a convention that local variables with leading underscores are designed to be unread, e.g:

```ts
const [a, _, c, d, e, f] = something
// or
const [a, _b, _c, d, e, f] = something
```

Moreover, tslint recently [temporarily deprecated their no-unused-variable rule](https://github.com/palantir/tslint/pull/2256) in favour of the [new compiler flags](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals) which take leading underscores into account.

I suggest we:

* ignore variables that start with an underscore in `js/unused-local-variable`
* create a new query that finds variables that suggests they should be unused, but are actually used.

**Comment by xiemaisi** [comment]
> It's a convention (...)

I'm sure you're right, but could we have a reference for that convention? I'd also like to point out that in the examples you give you should be able to just omit the `_*` variables altogether:

```js
const [a, , c, d, e, f] = something
```

**Comment by samlanning** [comment]
> I'm sure you're right, but could we have a reference for that convention?

Here are a few of places:

* [Typescript compiler's behaviour for compiler flags `--noUnusedParameters` and `--noUnusedLocals`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals)

  > Parameters declaration with names starting with `_` are exempt from the unused parameter checking. e.g.:
  > ```js
  > function returnNull(_a) { // OK
  >     return null;
  > }
  > ```

  (If we decide it's not a widely-enough used convention for JS, we could potentially enable it for TS only)

* [ESLint documentation on `no-unused-vars`. Uses prefix underscores as an example for the `argsIgnorePattern` option](https://eslint.org/docs/rules/no-unused-vars#argsignorepattern):

  > The `argsIgnorePattern` option specifies exceptions not to check for usage: arguments whose names match a regexp pattern. For example, variables whose names begin with an underscore.

* [Ruby's community coding conventions](https://github.com/rubocop-hq/ruby-style-guide):

  > Prefix with `_` unused block parameters and local variables. It's also acceptable to use just `_` (although it's a bit less descriptive). This convention is recognized by the Ruby interpreter and tools like RuboCop and will suppress their unused variable warnings.

>  I'd also like to point out that in the examples you give you should be able to just omit the _* variables altogether

Ah yes!

**Comment by xiemaisi** [comment]
OK, thanks, that looks fairly widely accepted.

> If we decide it's not a widely-enough used convention for JS, we could potentially enable it for TS only

We could, but to be honest I doubt we'll lose any interesting results by enabling it for JS as well.
