### ISSUE TITLE
False positive in js/unused-local-variable with aliased destructuring assignments

### ISSUE THREAD

**Issue by samlanning** [Semmle/ql#664]
As detailed here: https://github.com/Shopify/quilt/pull/434#issuecomment-446246993

When doing [object destructuring with new variable names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_to_new_variable_names), we're determining the name of the variable incorrectly, and selecting the name of the property from the object being destructured instead.

E.g:

```ts
const {foo: bar} = {foo: 'foo', bar: 'bar'}
// foo is undefined
// bar is now a constant variable
```

Example FP: https://lgtm.com/projects/g/Shopify/quilt/snapshot/b8540654494cf2f30293faccbaee3b4c19287e76/files/packages/react-google-analytics/src/GaJS.tsx#xf859505316cad831:1

**Comment by xiemaisi** [comment]
Seems to be TypeScript-specific; the following example triggers an FP when analysed as TypeScript, but not when analysed as JavaScript (@asger-semmle):

```js
function f(o) {
  const { p: v = [] } = o;
  return v;
}
```

**Comment by asger-semmle** [comment]
Should be fixed by https://github.com/Semmle/ql/pull/667.

Unfortunately this did not make it into 1.19 or this week's distribution upgrade, but we'll try and get it into a patch release if there is one.
