### ISSUE TITLE
False positive for js/react/unused-or-undefined-state-property

### ISSUE THREAD

**Issue by samlanning** [Semmle/ql#670]
`js/react/unused-or-undefined-state-property` doesn't take into account the static method `getDerivedStateFromProps`.

See example: https://lgtm.com/projects/g/ant-design/ant-design/snapshot/395c5ddd8d3db88e9c34cf332ec77b3c34077cfe/files/components/tag/index.tsx#xf4fd4ef83f04a4fd:1

The state property `mounted` is read in `getDerivedStateFromProps()` on line 48.

**Comment by esben-semmle** [comment]
We merged https://github.com/Semmle/ql/pull/607 last week, it adds support for: `getSnapshotBeforeUpdate`, `shouldComponentUpdate` and `getDerivedStateFromProps`. The fix should be online soon.
