### ISSUE TITLE
JavaScript: false positive in js/unbound-event-handler-receiver

### ISSUE THREAD

**Issue by imsolost** [Semmle/ql#955]
Projects that use [autobind](https://www.npmjs.com/package/react-autobind) should not display this error, as the methods are automatically bound in the constructor. 

[Link to error on LGTM](https://lgtm.com/projects/g/uber/deck.gl/snapshot/82d7ccafbce963a578774502857c23ea55dbc0a3/files/showcases/wind/src/app.js?sort=name&dir=ASC&mode=heatmap#x71ffff1ad7d1c926:1)

[Link to autobind in constructor.](https://lgtm.com/projects/g/uber/deck.gl/snapshot/82d7ccafbce963a578774502857c23ea55dbc0a3/files/showcases/wind/src/app.js?sort=name&dir=ASC&mode=heatmap#L42)

**Comment by esben-semmle** [comment]
Thanks. A fix is inbound.
